from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class Bridge(Protocol):
    # Workbook/sheet operations
    def get_active_sheet_id(self) -> str: ...

    def get_sheet_id(self, name: str) -> Optional[str]: ...

    def create_sheet(self, name: str) -> str: ...

    def get_sheet_name(self, sheet_id: str) -> str: ...

    def rename_sheet(self, sheet_id: str, name: str) -> None: ...

    # Range/cell operations
    def get_range_values(self, range_ref: Dict[str, Any]) -> List[List[Any]]: ...

    def set_range_values(self, range_ref: Dict[str, Any], values: Any) -> None: ...

    def set_cell_value(self, range_ref: Dict[str, Any], value: Any) -> None: ...

    def get_cell_formula(self, range_ref: Dict[str, Any]) -> Optional[str]: ...

    def set_cell_formula(self, range_ref: Dict[str, Any], formula: str) -> None: ...

    def clear_range(self, range_ref: Dict[str, Any]) -> None: ...

