function makeIdentifier(prefix, name) {
  const cleaned = name.replace(/[^a-zA-Z0-9_]/g, "_");
  const candidate = `${prefix}${cleaned}`;
  if (/^[a-zA-Z_]/.test(candidate)) return candidate;
  return `${prefix}_${cleaned}`;
}

function literal(value) {
  return JSON.stringify(value, null, 2);
}

export function generateTypeScriptMacro(actions) {
  const lines = [];
  lines.push("// Generated by Formula Macro Recorder");
  lines.push("//");
  lines.push("// This script is intended to be run with the Formula Script Runtime.");
  lines.push("");

  const sheetVars = new Map();

  const ensureSheetVar = (sheetName) => {
    const existing = sheetVars.get(sheetName);
    if (existing) return existing;
    const id = makeIdentifier("sheet_", sheetName);
    sheetVars.set(sheetName, id);
    lines.push(`const ${id} = ctx.workbook.getSheet(${literal(sheetName)});`);
    return id;
  };

  for (const action of actions) {
    switch (action.type) {
      case "setCellValue": {
        const sheetVar = ensureSheetVar(action.sheetName);
        lines.push(`await ${sheetVar}.getRange(${literal(action.address)}).setValue(${literal(action.value)});`);
        break;
      }
      case "setRangeValues": {
        const sheetVar = ensureSheetVar(action.sheetName);
        lines.push(
          `await ${sheetVar}.getRange(${literal(action.address)}).setValues(${literal(action.values)});`,
        );
        break;
      }
      case "setFormat": {
        const sheetVar = ensureSheetVar(action.sheetName);
        lines.push(
          `await ${sheetVar}.getRange(${literal(action.address)}).setFormat(${literal(action.format)});`,
        );
        break;
      }
      case "setSelection": {
        lines.push(
          `await ctx.workbook.setSelection(${literal(action.sheetName)}, ${literal(action.address)});`,
        );
        break;
      }
      default: {
        // Exhaustiveness.
        throw new Error(`Unhandled action: ${JSON.stringify(action)}`);
      }
    }
  }

  lines.push("");
  return lines.join("\n");
}
