import type { RibbonTabDefinition } from "../ribbonSchema.js";

export const homeTab: RibbonTabDefinition = {
  id: "home",
  label: "Home",
  groups: [
    {
      id: "home.clipboard",
      label: "Clipboard",
      buttons: [
        {
          id: "clipboard.paste",
          label: "Paste",
          ariaLabel: "Paste",
          iconId: "paste",
          kind: "dropdown",
          size: "large",
          testId: "ribbon-paste",
          menuItems: [
            { id: "clipboard.paste", label: "Paste", ariaLabel: "Paste", iconId: "paste" },
            { id: "clipboard.pasteSpecial.values", label: "Paste Values", ariaLabel: "Paste Values" },
            { id: "clipboard.pasteSpecial.formulas", label: "Paste Formulas", ariaLabel: "Paste Formulas", iconId: "function" },
            { id: "clipboard.pasteSpecial.formats", label: "Paste Formatting", ariaLabel: "Paste Formatting", iconId: "palette" },
            { id: "clipboard.pasteSpecial.transpose", label: "Transpose", ariaLabel: "Transpose", iconId: "refresh" },
          ],
        },
        {
          id: "clipboard.pasteSpecial",
          label: "Paste Special",
          ariaLabel: "Paste Special",
          iconId: "pasteSpecial",
          kind: "dropdown",
          size: "small",
          menuItems: [
            { id: "clipboard.pasteSpecial", label: "Paste Special…", ariaLabel: "Paste Special", iconId: "pasteSpecial" },
            { id: "clipboard.pasteSpecial.values", label: "Values", ariaLabel: "Paste Values" },
            { id: "clipboard.pasteSpecial.formulas", label: "Formulas", ariaLabel: "Paste Formulas", iconId: "function" },
            { id: "clipboard.pasteSpecial.formats", label: "Formats", ariaLabel: "Paste Formats", iconId: "palette" },
            { id: "clipboard.pasteSpecial.transpose", label: "Transpose", ariaLabel: "Transpose", iconId: "refresh" },
          ],
        },
        { id: "clipboard.cut", label: "Cut", ariaLabel: "Cut", iconId: "cut", size: "icon" },
        { id: "clipboard.copy", label: "Copy", ariaLabel: "Copy", iconId: "copy", size: "icon" },
        { id: "format.toggleFormatPainter", label: "Format Painter", ariaLabel: "Format Painter", iconId: "formatPainter", size: "small" },
        {
          id: "home.clipboard.clipboardPane",
          label: "Clipboard",
          ariaLabel: "Open Clipboard",
          iconId: "clipboardPane",
          kind: "dropdown",
          size: "small",
          menuItems: [
            { id: "home.clipboard.clipboardPane.open", label: "Open Clipboard", ariaLabel: "Open Clipboard", iconId: "clipboardPane" },
            { id: "home.clipboard.clipboardPane.clearAll", label: "Clear All", ariaLabel: "Clear Clipboard", iconId: "clear" },
            { id: "home.clipboard.clipboardPane.options", label: "Options…", ariaLabel: "Clipboard Options", iconId: "settings" },
          ],
        },
      ],
    },
    {
      id: "home.debug.ai",
      label: "AI",
      buttons: [
        {
          id: "view.togglePanel.aiChat",
          label: "AI",
          ariaLabel: "Toggle AI panel",
          iconId: "sparkles",
          testId: "open-panel-ai-chat",
          size: "icon",
        },
        {
          id: "ai.inlineEdit",
          label: "Inline Edit",
          ariaLabel: "Inline AI Edit",
          iconId: "sparkles",
          testId: "open-inline-ai-edit",
          size: "icon",
        },
      ],
    },
    {
      id: "home.debug.aiLegacy",
      label: "AI (legacy)",
      buttons: [
        {
          id: "view.togglePanel.aiChat",
          label: "AI (legacy)",
          ariaLabel: "Toggle AI panel",
          iconId: "sparkles",
          testId: "open-ai-panel",
          size: "icon",
        },
      ],
    },
    {
      id: "home.find",
      label: "Find",
      buttons: [
        {
          id: "home.editing.findSelect",
          label: "Find & Select",
          ariaLabel: "Find and Select",
          iconId: "find",
          kind: "dropdown",
          menuItems: [
            { id: "edit.find", label: "Find", ariaLabel: "Find", iconId: "find", testId: "ribbon-find" },
            { id: "edit.replace", label: "Replace", ariaLabel: "Replace", iconId: "replace", testId: "ribbon-replace" },
            { id: "navigation.goTo", label: "Go To", ariaLabel: "Go To", iconId: "goTo", testId: "ribbon-goto" },
          ],
        },
      ],
    },
    {
      id: "home.font",
      label: "Font",
      buttons: [
        {
          id: "home.font.fontName",
          label: "Font",
          ariaLabel: "Font",
          kind: "dropdown",
          size: "small",
          menuItems: [
            { id: "format.fontName.calibri", label: "Calibri", ariaLabel: "Calibri" },
            { id: "format.fontName.arial", label: "Arial", ariaLabel: "Arial" },
            { id: "format.fontName.times", label: "Times New Roman", ariaLabel: "Times New Roman" },
            { id: "format.fontName.courier", label: "Courier New", ariaLabel: "Courier New" },
          ],
        },
        {
          id: "home.font.fontSize",
          label: "Size",
          ariaLabel: "Font Size",
          iconId: "fontSize",
          kind: "dropdown",
          size: "small",
          menuItems: [
            { id: "format.fontSize.8", label: "8", ariaLabel: "Font size 8" },
            { id: "format.fontSize.9", label: "9", ariaLabel: "Font size 9" },
            { id: "format.fontSize.10", label: "10", ariaLabel: "Font size 10" },
            { id: "format.fontSize.11", label: "11", ariaLabel: "Font size 11" },
            { id: "format.fontSize.12", label: "12", ariaLabel: "Font size 12" },
            { id: "format.fontSize.14", label: "14", ariaLabel: "Font size 14" },
            { id: "format.fontSize.16", label: "16", ariaLabel: "Font size 16" },
            { id: "format.fontSize.18", label: "18", ariaLabel: "Font size 18" },
            { id: "format.fontSize.20", label: "20", ariaLabel: "Font size 20" },
            { id: "format.fontSize.24", label: "24", ariaLabel: "Font size 24" },
            { id: "format.fontSize.28", label: "28", ariaLabel: "Font size 28" },
            { id: "format.fontSize.36", label: "36", ariaLabel: "Font size 36" },
            { id: "format.fontSize.48", label: "48", ariaLabel: "Font size 48" },
            { id: "format.fontSize.72", label: "72", ariaLabel: "Font size 72" },
          ],
        },
        { id: "format.increaseFontSize", label: "Grow Font", ariaLabel: "Increase Font Size", iconId: "increaseFont", size: "icon" },
        { id: "format.decreaseFontSize", label: "Shrink Font", ariaLabel: "Decrease Font Size", iconId: "decreaseFont", size: "icon" },
        { id: "format.toggleBold", label: "Bold", ariaLabel: "Bold", iconId: "bold", kind: "toggle", size: "icon" },
        { id: "format.toggleItalic", label: "Italic", ariaLabel: "Italic", iconId: "italic", kind: "toggle", size: "icon" },
        { id: "format.toggleUnderline", label: "Underline", ariaLabel: "Underline", iconId: "underline", kind: "toggle", size: "icon" },
        { id: "format.toggleStrikethrough", label: "Strike", ariaLabel: "Strikethrough", iconId: "strikethrough", kind: "toggle", size: "icon" },
        { id: "home.font.subscript", label: "Subscript", ariaLabel: "Subscript", iconId: "subscript", kind: "toggle", size: "icon" },
        { id: "home.font.superscript", label: "Superscript", ariaLabel: "Superscript", iconId: "superscript", kind: "toggle", size: "icon" },
        {
          id: "home.font.borders",
          label: "Borders",
          ariaLabel: "Borders",
          iconId: "borders",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            { id: "format.borders.none", label: "No Border", ariaLabel: "No Border", iconId: "clear" },
            { id: "format.borders.all", label: "All Borders", ariaLabel: "All Borders", iconId: "borders" },
            { id: "format.borders.outside", label: "Outside Borders", ariaLabel: "Outside Borders", iconId: "borders" },
            { id: "format.borders.thickBox", label: "Thick Box Border", ariaLabel: "Thick Box Border", iconId: "borders" },
            { id: "format.borders.bottom", label: "Bottom Border", ariaLabel: "Bottom Border", iconId: "arrowDown" },
            { id: "format.borders.top", label: "Top Border", ariaLabel: "Top Border", iconId: "arrowUp" },
            { id: "format.borders.left", label: "Left Border", ariaLabel: "Left Border", iconId: "arrowLeft" },
            { id: "format.borders.right", label: "Right Border", ariaLabel: "Right Border", iconId: "arrowRight" },
          ],
        },
        {
          id: "home.font.fillColor",
          label: "Fill",
          ariaLabel: "Fill Color",
          iconId: "fillColor",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            // Keep command ids aligned with desktop CommandRegistry wiring so core
            // formatting actions work out of the box.
            { id: "format.fillColor.none", label: "No Fill", ariaLabel: "No Fill", iconId: "fillColor" },
            { id: "format.fillColor.lightGray", label: "Light Gray", ariaLabel: "Light Gray Fill", iconId: "fillColor" },
            { id: "format.fillColor.yellow", label: "Yellow", ariaLabel: "Yellow Fill", iconId: "fillColor" },
            { id: "format.fillColor.blue", label: "Blue", ariaLabel: "Blue Fill", iconId: "fillColor" },
            { id: "format.fillColor.green", label: "Green", ariaLabel: "Green Fill", iconId: "fillColor" },
            { id: "format.fillColor.red", label: "Red", ariaLabel: "Red Fill", iconId: "fillColor" },
            { id: "format.fillColor.moreColors", label: "More Colors…", ariaLabel: "More Fill Colors", iconId: "palette" },
          ],
        },
        {
          id: "home.font.fontColor",
          label: "Color",
          ariaLabel: "Font Color",
          iconId: "fontColor",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            { id: "format.fontColor.automatic", label: "Automatic", ariaLabel: "Automatic Font Color", iconId: "fontColor" },
            { id: "format.fontColor.black", label: "Black", ariaLabel: "Black Font Color", iconId: "fontColor" },
            { id: "format.fontColor.blue", label: "Blue", ariaLabel: "Blue Font Color", iconId: "fontColor" },
            { id: "format.fontColor.red", label: "Red", ariaLabel: "Red Font Color", iconId: "fontColor" },
            { id: "format.fontColor.green", label: "Green", ariaLabel: "Green Font Color", iconId: "fontColor" },
            { id: "format.fontColor.moreColors", label: "More Colors…", ariaLabel: "More Font Colors", iconId: "palette" },
          ],
        },
        {
          id: "home.font.clearFormatting",
          label: "Clear",
          ariaLabel: "Clear Formatting",
          iconId: "clearFormatting",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            { id: "format.clearFormats", label: "Clear Formats", ariaLabel: "Clear Formats", iconId: "palette" },
            { id: "format.clearContents", label: "Clear Contents", ariaLabel: "Clear Contents", iconId: "clear" },
            { id: "format.clearAll", label: "Clear All", ariaLabel: "Clear All", iconId: "clear" },
          ],
        },
      ],
    },
    {
      id: "home.alignment",
      label: "Alignment",
      buttons: [
        { id: "format.alignTop", label: "Top", ariaLabel: "Top Align", iconId: "alignTop", size: "icon" },
        { id: "format.alignMiddle", label: "Middle", ariaLabel: "Middle Align", iconId: "alignMiddle", size: "icon" },
        { id: "format.alignBottom", label: "Bottom", ariaLabel: "Bottom Align", iconId: "alignBottom", size: "icon" },
        { id: "format.alignLeft", label: "Left", ariaLabel: "Align Left", iconId: "alignLeft", size: "icon" },
        { id: "format.alignCenter", label: "Center", ariaLabel: "Center", iconId: "alignCenter", size: "icon" },
        { id: "format.alignRight", label: "Right", ariaLabel: "Align Right", iconId: "alignRight", size: "icon" },
        {
          id: "home.alignment.orientation",
          label: "Orientation",
          ariaLabel: "Orientation",
          iconId: "orientation",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            { id: "format.textRotation.angleCounterclockwise", label: "Angle Counterclockwise", ariaLabel: "Angle Counterclockwise", iconId: "orientation" },
            { id: "format.textRotation.angleClockwise", label: "Angle Clockwise", ariaLabel: "Angle Clockwise", iconId: "orientation" },
            { id: "format.textRotation.verticalText", label: "Vertical Text", ariaLabel: "Vertical Text", iconId: "arrowUpDown" },
            { id: "format.textRotation.rotateUp", label: "Rotate Text Up", ariaLabel: "Rotate Text Up", iconId: "arrowUp" },
            { id: "format.textRotation.rotateDown", label: "Rotate Text Down", ariaLabel: "Rotate Text Down", iconId: "arrowDown" },
            { id: "format.openAlignmentDialog", label: "Format Cell Alignment…", ariaLabel: "Format Cell Alignment", iconId: "settings" },
          ],
        },
        { id: "format.toggleWrapText", label: "Wrap Text", ariaLabel: "Wrap Text", iconId: "wrapText", kind: "toggle", size: "small" },
        {
          id: "home.alignment.mergeCenter",
          label: "Merge & Center",
          ariaLabel: "Merge and Center",
          iconId: "mergeCenter",
          kind: "dropdown",
          size: "small",
          menuItems: [
            { id: "home.alignment.mergeCenter.mergeCenter", label: "Merge & Center", ariaLabel: "Merge and Center", iconId: "mergeCenter" },
            { id: "home.alignment.mergeCenter.mergeAcross", label: "Merge Across", ariaLabel: "Merge Across", iconId: "arrowLeftRight" },
            { id: "home.alignment.mergeCenter.mergeCells", label: "Merge Cells", ariaLabel: "Merge Cells", iconId: "mergeCenter" },
            { id: "home.alignment.mergeCenter.unmergeCells", label: "Unmerge Cells", ariaLabel: "Unmerge Cells", iconId: "close" },
          ],
        },
        { id: "format.increaseIndent", label: "Indent", ariaLabel: "Increase Indent", iconId: "increaseIndent", size: "icon" },
        { id: "format.decreaseIndent", label: "Outdent", ariaLabel: "Decrease Indent", iconId: "decreaseIndent", size: "icon" },
      ],
    },
    {
      id: "home.number",
      label: "Number",
      buttons: [
        {
          id: "home.number.numberFormat",
          label: "General",
          ariaLabel: "Number Format",
          iconId: "numberFormat",
          kind: "dropdown",
          size: "small",
          menuItems: [
            { id: "format.numberFormat.general", label: "General", ariaLabel: "General", iconId: "numberFormat" },
            { id: "format.numberFormat.number", label: "Number", ariaLabel: "Number", iconId: "numberFormat" },
            { id: "format.numberFormat.currency", label: "Currency", ariaLabel: "Currency", iconId: "currency" },
            { id: "format.numberFormat.accounting", label: "Accounting", ariaLabel: "Accounting", iconId: "currency" },
            { id: "format.numberFormat.shortDate", label: "Short Date", ariaLabel: "Short Date", iconId: "calendar" },
            { id: "format.numberFormat.longDate", label: "Long Date", ariaLabel: "Long Date", iconId: "calendar" },
            { id: "format.numberFormat.time", label: "Time", ariaLabel: "Time", iconId: "clock" },
            { id: "format.numberFormat.percent", label: "Percentage", ariaLabel: "Percentage", iconId: "percent" },
            { id: "format.numberFormat.fraction", label: "Fraction", ariaLabel: "Fraction", iconId: "divide" },
            { id: "format.numberFormat.scientific", label: "Scientific", ariaLabel: "Scientific", iconId: "numberFormat" },
            { id: "format.numberFormat.text", label: "Text", ariaLabel: "Text", iconId: "fontSize" },
          ],
        },
        {
          id: "format.numberFormat.accounting",
          label: "Accounting",
          ariaLabel: "Accounting Number Format",
          iconId: "currency",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            { id: "format.numberFormat.accounting.usd", label: "$ (Dollar)", ariaLabel: "Dollar", iconId: "currency" },
            { id: "format.numberFormat.accounting.eur", label: "€ (Euro)", ariaLabel: "Euro", iconId: "currency" },
            { id: "format.numberFormat.accounting.gbp", label: "£ (Pound)", ariaLabel: "Pound", iconId: "currency" },
            { id: "format.numberFormat.accounting.jpy", label: "¥ (Yen)", ariaLabel: "Yen", iconId: "currency" },
          ],
        },
        { id: "format.numberFormat.percent", label: "Percent", ariaLabel: "Percent Style", iconId: "percent", size: "icon" },
        { id: "format.numberFormat.shortDate", label: "Date", ariaLabel: "Date", iconId: "calendar", size: "icon" },
        { id: "format.numberFormat.commaStyle", label: "Comma", ariaLabel: "Comma Style", iconId: "comma", size: "icon" },
        { id: "format.numberFormat.increaseDecimal", label: "Inc Decimal", ariaLabel: "Increase Decimal", iconId: "increaseDecimal", size: "icon" },
        { id: "format.numberFormat.decreaseDecimal", label: "Dec Decimal", ariaLabel: "Decrease Decimal", iconId: "decreaseDecimal", size: "icon" },
        {
          id: "home.number.moreFormats",
          label: "More",
          ariaLabel: "More Number Formats",
          iconId: "moreFormats",
          kind: "dropdown",
          size: "icon",
          menuItems: [
            { id: "format.openFormatCells", label: "Format Cells…", ariaLabel: "Format Cells", iconId: "settings" },
            { id: "home.number.moreFormats.custom", label: "Custom…", ariaLabel: "Custom Number Format", iconId: "edit" },
          ],
        },
        { id: "format.openFormatCells", label: "Format Cells…", ariaLabel: "Format Cells", iconId: "settings", size: "small", testId: "ribbon-format-cells" },
      ],
    },
    {
      id: "home.styles",
      label: "Styles",
      buttons: [
        {
          id: "home.styles.conditionalFormatting",
          label: "Conditional Formatting",
          ariaLabel: "Conditional Formatting",
          iconId: "conditionalFormatting",
          kind: "dropdown",
          size: "large",
          menuItems: [
            { id: "home.styles.conditionalFormatting.highlightCellsRules", label: "Highlight Cells Rules", ariaLabel: "Highlight Cells Rules", iconId: "fillColor" },
            { id: "home.styles.conditionalFormatting.topBottomRules", label: "Top/Bottom Rules", ariaLabel: "Top or Bottom Rules", iconId: "arrowUp" },
            { id: "home.styles.conditionalFormatting.dataBars", label: "Data Bars", ariaLabel: "Data Bars", iconId: "chart" },
            { id: "home.styles.conditionalFormatting.colorScales", label: "Color Scales", ariaLabel: "Color Scales", iconId: "palette" },
            { id: "home.styles.conditionalFormatting.iconSets", label: "Icon Sets", ariaLabel: "Icon Sets", iconId: "sparkles" },
            { id: "home.styles.conditionalFormatting.manageRules", label: "Manage Rules…", ariaLabel: "Manage Rules", iconId: "settings" },
            { id: "home.styles.conditionalFormatting.clearRules", label: "Clear Rules", ariaLabel: "Clear Rules", iconId: "close" },
          ],
        },
        {
          id: "home.styles.formatAsTable",
          label: "Format as Table",
          ariaLabel: "Format as Table",
          iconId: "formatAsTable",
          kind: "dropdown",
          size: "large",
          menuItems: [
            { id: "home.styles.formatAsTable.light", label: "Light", ariaLabel: "Light table styles", iconId: "file" },
            { id: "home.styles.formatAsTable.medium", label: "Medium", ariaLabel: "Medium table styles", iconId: "fillColor" },
            { id: "home.styles.formatAsTable.dark", label: "Dark", ariaLabel: "Dark table styles", iconId: "fillColor" },
            { id: "home.styles.formatAsTable.newStyle", label: "New Table Style…", ariaLabel: "New Table Style", iconId: "plus" },
          ],
        },
        {
          id: "home.styles.cellStyles",
          label: "Cell Styles",
          ariaLabel: "Cell Styles",
          iconId: "cellStyles",
          kind: "dropdown",
          size: "large",
          menuItems: [
            { id: "home.styles.cellStyles.goodBadNeutral", label: "Good, Bad, and Neutral", ariaLabel: "Good Bad and Neutral", iconId: "fillColor" },
            { id: "home.styles.cellStyles.dataModel", label: "Data Model", ariaLabel: "Data Model styles", iconId: "chart" },
            { id: "home.styles.cellStyles.titlesHeadings", label: "Titles and Headings", ariaLabel: "Titles and Headings", iconId: "tag" },
            { id: "home.styles.cellStyles.numberFormat", label: "Number Format", ariaLabel: "Number Format styles", iconId: "numberFormat" },
            { id: "home.styles.cellStyles.newStyle", label: "New Cell Style…", ariaLabel: "New Cell Style", iconId: "plus" },
          ],
        },
      ],
    },
    {
      id: "home.cells",
      label: "Cells",
      buttons: [
        {
          id: "home.cells.insert",
          label: "Insert",
          ariaLabel: "Insert Cells",
          iconId: "insertCells",
          kind: "dropdown",
          menuItems: [
            { id: "home.cells.insert.insertCells", label: "Insert Cells…", ariaLabel: "Insert Cells", iconId: "insertCells" },
            { id: "home.cells.insert.insertSheetRows", label: "Insert Sheet Rows", ariaLabel: "Insert Sheet Rows", iconId: "insertRows" },
            { id: "home.cells.insert.insertSheetColumns", label: "Insert Sheet Columns", ariaLabel: "Insert Sheet Columns", iconId: "insertColumns" },
            { id: "home.cells.insert.insertSheet", label: "Insert Sheet", ariaLabel: "Insert Sheet", iconId: "insertSheet" },
          ],
        },
        {
          id: "home.cells.delete",
          label: "Delete",
          ariaLabel: "Delete Cells",
          iconId: "deleteCells",
          kind: "dropdown",
          menuItems: [
            { id: "home.cells.delete.deleteCells", label: "Delete Cells…", ariaLabel: "Delete Cells", iconId: "deleteCells" },
            { id: "home.cells.delete.deleteSheetRows", label: "Delete Sheet Rows", ariaLabel: "Delete Sheet Rows", iconId: "deleteCells" },
            { id: "home.cells.delete.deleteSheetColumns", label: "Delete Sheet Columns", ariaLabel: "Delete Sheet Columns", iconId: "deleteCells" },
            { id: "home.cells.delete.deleteSheet", label: "Delete Sheet", ariaLabel: "Delete Sheet", iconId: "deleteSheet" },
          ],
        },
        {
          id: "home.cells.format",
          label: "Format",
          ariaLabel: "Format Cells",
          iconId: "settings",
          kind: "dropdown",
          menuItems: [
            { id: "format.openFormatCells", label: "Format Cells…", ariaLabel: "Format Cells", iconId: "settings" },
            { id: "home.cells.format.rowHeight", label: "Row Height…", ariaLabel: "Row Height", iconId: "arrowUpDown" },
            { id: "home.cells.format.columnWidth", label: "Column Width…", ariaLabel: "Column Width", iconId: "arrowLeftRight" },
            { id: "home.cells.format.organizeSheets", label: "Organize Sheets", ariaLabel: "Organize Sheets", iconId: "folderOpen" },
          ],
        },
      ],
    },
    {
      id: "home.editing",
      label: "Editing",
      buttons: [
        {
          id: "edit.autoSum",
          label: "AutoSum",
          ariaLabel: "AutoSum",
          iconId: "autoSum",
          kind: "dropdown",
          menuItems: [
            { id: "edit.autoSum", label: "Sum", ariaLabel: "Sum", iconId: "autoSum" },
            { id: "home.editing.autoSum.average", label: "Average", ariaLabel: "Average", iconId: "divide" },
            { id: "home.editing.autoSum.countNumbers", label: "Count Numbers", ariaLabel: "Count Numbers", iconId: "hash" },
            { id: "home.editing.autoSum.max", label: "Max", ariaLabel: "Max", iconId: "arrowUp" },
            { id: "home.editing.autoSum.min", label: "Min", ariaLabel: "Min", iconId: "arrowDown" },
            { id: "home.editing.autoSum.moreFunctions", label: "More Functions…", ariaLabel: "More Functions", iconId: "function" },
          ],
        },
        {
          id: "home.editing.fill",
          label: "Fill",
          ariaLabel: "Fill",
          iconId: "fillDown",
          kind: "dropdown",
          menuItems: [
            { id: "edit.fillDown", label: "Down", ariaLabel: "Fill Down", iconId: "arrowDown" },
            { id: "edit.fillRight", label: "Right", ariaLabel: "Fill Right", iconId: "arrowRight" },
            { id: "home.editing.fill.up", label: "Up", ariaLabel: "Fill Up", iconId: "arrowUp" },
            { id: "home.editing.fill.left", label: "Left", ariaLabel: "Fill Left", iconId: "arrowLeft" },
            { id: "home.editing.fill.series", label: "Series…", ariaLabel: "Series", iconId: "moreFormats" },
          ],
        },
        {
          id: "home.editing.clear",
          label: "Clear",
          ariaLabel: "Clear",
          iconId: "clear",
          kind: "dropdown",
          menuItems: [
            { id: "home.editing.clear.clearAll", label: "Clear All", ariaLabel: "Clear All", iconId: "clear" },
            { id: "home.editing.clear.clearFormats", label: "Clear Formats", ariaLabel: "Clear Formats", iconId: "palette" },
            { id: "home.editing.clear.clearContents", label: "Clear Contents", ariaLabel: "Clear Contents", iconId: "clear" },
            { id: "home.editing.clear.clearComments", label: "Clear Comments", ariaLabel: "Clear Comments", iconId: "comment" },
            { id: "home.editing.clear.clearHyperlinks", label: "Clear Hyperlinks", ariaLabel: "Clear Hyperlinks", iconId: "link" },
          ],
        },
        {
          id: "home.editing.sortFilter",
          label: "Sort & Filter",
          ariaLabel: "Sort and Filter",
          iconId: "sortFilter",
          kind: "dropdown",
          menuItems: [
            { id: "home.editing.sortFilter.sortAtoZ", label: "Sort A to Z", ariaLabel: "Sort A to Z", iconId: "sort" },
            { id: "home.editing.sortFilter.sortZtoA", label: "Sort Z to A", ariaLabel: "Sort Z to A", iconId: "sort" },
            { id: "home.editing.sortFilter.customSort", label: "Custom Sort…", ariaLabel: "Custom Sort", iconId: "settings" },
            { id: "home.editing.sortFilter.filter", label: "Filter", ariaLabel: "Filter", iconId: "filter" },
            { id: "home.editing.sortFilter.clear", label: "Clear", ariaLabel: "Clear", iconId: "close" },
            { id: "home.editing.sortFilter.reapply", label: "Reapply", ariaLabel: "Reapply", iconId: "refresh" },
          ],
        },
      ],
    },
    {
      id: "home.debug.panels",
      label: "Panels",
      buttons: [
        {
          id: "view.togglePanel.aiAudit",
          label: "Audit log (alt)",
          ariaLabel: "Toggle AI audit log panel",
          iconId: "file",
          testId: "open-panel-ai-audit",
          size: "icon",
        },
        {
          id: "view.togglePanel.dataQueries",
          label: "Queries",
          ariaLabel: "Toggle Queries panel",
          iconId: "search",
          testId: "open-data-queries-panel",
          size: "icon",
        },
        {
          id: "view.togglePanel.macros",
          label: "Macros",
          ariaLabel: "Toggle Macros panel",
          iconId: "file",
          testId: "open-macros-panel",
          size: "icon",
        },
        {
          id: "view.togglePanel.scriptEditor",
          label: "Scripts",
          ariaLabel: "Toggle Script editor panel",
          iconId: "code",
          testId: "open-script-editor-panel",
          size: "icon",
        },
        {
          id: "view.togglePanel.python",
          label: "Python",
          ariaLabel: "Toggle Python panel",
          iconId: "code",
          testId: "open-python-panel",
          size: "icon",
        },
        {
          id: "view.togglePanel.extensions",
          label: "Extensions",
          ariaLabel: "Toggle Extensions panel",
          iconId: "puzzle",
          testId: "open-extensions-panel",
          size: "icon",
        },
        {
          id: "view.togglePanel.vbaMigrate",
          label: "Migrate Macros",
          ariaLabel: "Toggle VBA migrate panel",
          iconId: "settings",
          testId: "open-vba-migrate-panel",
          size: "icon",
        },
        {
          id: "comments.togglePanel",
          label: "Comments",
          ariaLabel: "Toggle Comments panel",
          iconId: "comment",
          testId: "open-comments-panel",
          size: "icon",
        },
      ],
    },
    {
      id: "home.debug.panelsLegacy",
      label: "Panels (legacy)",
      buttons: [
        {
          id: "view.togglePanel.aiAudit",
          label: "Audit log (legacy)",
          ariaLabel: "Toggle AI audit log panel",
          iconId: "file",
          testId: "open-ai-audit-panel",
          size: "icon",
        },
      ],
    },
    {
      id: "home.debug.auditing",
      label: "Auditing",
      buttons: [
        {
          id: "audit.togglePrecedents",
          label: "Trace precedents",
          ariaLabel: "Trace precedents",
          iconId: "arrowLeft",
          testId: "audit-precedents",
          size: "icon",
        },
        {
          id: "audit.toggleDependents",
          label: "Trace dependents",
          ariaLabel: "Trace dependents",
          iconId: "arrowRight",
          testId: "audit-dependents",
          size: "icon",
        },
        {
          id: "audit.toggleTransitive",
          label: "Transitive",
          ariaLabel: "Toggle transitive auditing",
          iconId: "refresh",
          testId: "audit-transitive",
          size: "icon",
        },
      ],
    },
    {
      id: "home.debug.split",
      label: "Split view",
      buttons: [
        {
          id: "view.splitVertical",
          label: "Split vertical",
          ariaLabel: "Split vertically",
          iconId: "arrowLeftRight",
          testId: "split-vertical",
          size: "icon",
        },
        {
          id: "view.splitHorizontal",
          label: "Split horizontal",
          ariaLabel: "Split horizontally",
          iconId: "arrowUpDown",
          testId: "split-horizontal",
          size: "icon",
        },
        { id: "view.splitNone", label: "Unsplit", ariaLabel: "Remove split", iconId: "close", testId: "split-none", size: "icon" },
      ],
    },
    {
      id: "home.debug.freeze",
      label: "Freeze",
      buttons: [
        { id: "view.freezePanes", label: "Freeze Panes", ariaLabel: "Freeze Panes", iconId: "lock", testId: "freeze-panes", size: "icon" },
        { id: "view.freezeTopRow", label: "Freeze Top Row", ariaLabel: "Freeze Top Row", iconId: "arrowUp", testId: "freeze-top-row", size: "icon" },
        { id: "view.freezeFirstColumn", label: "Freeze First Column", ariaLabel: "Freeze First Column", iconId: "arrowLeft", testId: "freeze-first-column", size: "icon" },
        { id: "view.unfreezePanes", label: "Unfreeze Panes", ariaLabel: "Unfreeze Panes", iconId: "chart", testId: "unfreeze-panes", size: "icon" },
      ],
    },
  ],
};
