import type { RibbonTabDefinition } from "../ribbonSchema.js";

export const insertTab: RibbonTabDefinition = {
  id: "insert",
  label: "Insert",
  groups: [
    {
      id: "insert.tables",
      label: "Tables",
      buttons: [
        {
          id: "view.insertPivotTable",
          label: "PivotTable",
          ariaLabel: "PivotTable",
          iconId: "chart",
          kind: "dropdown",
          size: "large",
          testId: "ribbon-insert-pivot-table",
          menuItems: [
            { id: "view.insertPivotTable", label: "PivotTable…", ariaLabel: "PivotTable", iconId: "chart" },
            { id: "insert.tables.pivotTable.fromTableRange", label: "From Table/Range…", ariaLabel: "PivotTable from Table or Range", iconId: "formatAsTable" },
            { id: "insert.tables.pivotTable.fromExternal", label: "From External Data…", ariaLabel: "PivotTable from External Data", iconId: "globe" },
            { id: "insert.tables.pivotTable.fromDataModel", label: "From Data Model…", ariaLabel: "PivotTable from Data Model", iconId: "puzzle" },
          ],
        },
        {
          id: "insert.tables.recommendedPivotTables",
          label: "Recommended PivotTables",
          ariaLabel: "Recommended PivotTables",
          iconId: "sparkles",
          kind: "dropdown",
          menuItems: [
            {
              id: "insert.tables.recommendedPivotTables",
              label: "Recommended PivotTables…",
              ariaLabel: "Recommended PivotTables",
              iconId: "sparkles",
            },
          ],
        },
        { id: "insert.tables.table", label: "Table", ariaLabel: "Table", iconId: "formatAsTable", size: "large" },
      ],
    },
    {
      id: "insert.pivotcharts",
      label: "PivotCharts",
      buttons: [
        { id: "insert.pivotcharts.pivotChart", label: "PivotChart", ariaLabel: "PivotChart", iconId: "chart", kind: "dropdown", size: "large" },
        { id: "insert.pivotcharts.recommendedPivotCharts", label: "Recommended PivotCharts", ariaLabel: "Recommended PivotCharts", iconId: "sparkles", kind: "dropdown" },
      ],
    },
    {
      id: "insert.illustrations",
      label: "Illustrations",
      buttons: [
        {
          id: "insert.illustrations.pictures",
          label: "Pictures",
          ariaLabel: "Pictures",
          iconId: "image",
          kind: "dropdown",
          menuItems: [
            { id: "insert.illustrations.pictures.thisDevice", label: "This Device…", ariaLabel: "Pictures from this device", iconId: "image" },
            { id: "insert.illustrations.pictures.stockImages", label: "Stock Images…", ariaLabel: "Stock Images", iconId: "sparkles" },
            { id: "insert.illustrations.pictures.onlinePictures", label: "Online Pictures…", ariaLabel: "Online Pictures", iconId: "globe" },
          ],
        },
        { id: "insert.illustrations.onlinePictures", label: "Online Pictures", ariaLabel: "Online Pictures", iconId: "globe", kind: "dropdown" },
        {
          id: "insert.illustrations.shapes",
          label: "Shapes",
          ariaLabel: "Shapes",
          iconId: "shapes",
          kind: "dropdown",
          menuItems: [
            { id: "insert.illustrations.shapes.lines", label: "Lines", ariaLabel: "Lines", iconId: "shapes" },
            { id: "insert.illustrations.shapes.rectangles", label: "Rectangles", ariaLabel: "Rectangles", iconId: "shapes" },
            { id: "insert.illustrations.shapes.basicShapes", label: "Basic Shapes", ariaLabel: "Basic Shapes", iconId: "shapes" },
            { id: "insert.illustrations.shapes.arrows", label: "Block Arrows", ariaLabel: "Block Arrows", iconId: "arrowRight" },
            { id: "insert.illustrations.shapes.flowchart", label: "Flowchart", ariaLabel: "Flowchart", iconId: "puzzle" },
            { id: "insert.illustrations.shapes.callouts", label: "Callouts", ariaLabel: "Callouts", iconId: "comment" },
          ],
        },
        { id: "insert.illustrations.icons", label: "Icons", ariaLabel: "Icons", iconId: "sparkles", kind: "dropdown" },
        { id: "insert.illustrations.smartArt", label: "SmartArt", ariaLabel: "SmartArt", iconId: "puzzle", kind: "dropdown" },
        { id: "insert.illustrations.screenshot", label: "Screenshot", ariaLabel: "Screenshot", iconId: "image", kind: "dropdown" },
      ],
    },
    {
      id: "insert.addins",
      label: "Add-ins",
      buttons: [
        { id: "insert.addins.getAddins", label: "Get Add-ins", ariaLabel: "Get Add-ins", iconId: "plus", kind: "dropdown" },
        { id: "insert.addins.myAddins", label: "My Add-ins", ariaLabel: "My Add-ins", iconId: "puzzle", kind: "dropdown" },
      ],
    },
    {
      id: "insert.charts",
      label: "Charts",
      buttons: [
        {
          id: "insert.charts.recommendedCharts",
          label: "Recommended Charts",
          ariaLabel: "Recommended Charts",
          iconId: "sparkles",
          kind: "dropdown",
          size: "large",
          menuItems: [
            { id: "insert.charts.recommendedCharts", label: "Recommended Charts…", ariaLabel: "Recommended Charts", iconId: "sparkles" },
            { id: "insert.charts.recommendedCharts.column", label: "Column", ariaLabel: "Recommended Column Charts", iconId: "chart" },
            { id: "insert.charts.recommendedCharts.line", label: "Line", ariaLabel: "Recommended Line Charts", iconId: "chart" },
            { id: "insert.charts.recommendedCharts.pie", label: "Pie", ariaLabel: "Recommended Pie Charts", iconId: "chart" },
            { id: "insert.charts.recommendedCharts.more", label: "More…", ariaLabel: "More chart recommendations", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.column",
          label: "Column",
          ariaLabel: "Insert Column or Bar Chart",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.column.clusteredColumn", label: "Clustered Column", ariaLabel: "Clustered Column", iconId: "chart" },
            { id: "insert.charts.column.stackedColumn", label: "Stacked Column", ariaLabel: "Stacked Column", iconId: "chart" },
            { id: "insert.charts.column.stackedColumn100", label: "100% Stacked Column", ariaLabel: "100% Stacked Column", iconId: "chart" },
            { id: "insert.charts.column.more", label: "More Column Charts…", ariaLabel: "More Column Charts", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.line",
          label: "Line",
          ariaLabel: "Insert Line or Area Chart",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.line.line", label: "Line", ariaLabel: "Line", iconId: "chart" },
            { id: "insert.charts.line.lineWithMarkers", label: "Line with Markers", ariaLabel: "Line with Markers", iconId: "chart" },
            { id: "insert.charts.line.stackedArea", label: "Stacked Area", ariaLabel: "Stacked Area", iconId: "chart" },
            { id: "insert.charts.line.more", label: "More Line Charts…", ariaLabel: "More Line Charts", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.pie",
          label: "Pie",
          ariaLabel: "Insert Pie or Doughnut Chart",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.pie.pie", label: "Pie", ariaLabel: "Pie", iconId: "chart" },
            { id: "insert.charts.pie.doughnut", label: "Doughnut", ariaLabel: "Doughnut", iconId: "chart" },
            { id: "insert.charts.pie.more", label: "More Pie Charts…", ariaLabel: "More Pie Charts", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.bar",
          label: "Bar",
          ariaLabel: "Insert Bar Chart",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.bar.clusteredBar", label: "Clustered Bar", ariaLabel: "Clustered Bar", iconId: "chart" },
            { id: "insert.charts.bar.stackedBar", label: "Stacked Bar", ariaLabel: "Stacked Bar", iconId: "chart" },
            { id: "insert.charts.bar.more", label: "More Bar Charts…", ariaLabel: "More Bar Charts", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.area",
          label: "Area",
          ariaLabel: "Insert Area Chart",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.area.area", label: "Area", ariaLabel: "Area", iconId: "chart" },
            { id: "insert.charts.area.stackedArea", label: "Stacked Area", ariaLabel: "Stacked Area", iconId: "chart" },
            { id: "insert.charts.area.more", label: "More Area Charts…", ariaLabel: "More Area Charts", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.scatter",
          label: "Scatter",
          ariaLabel: "Insert Scatter (X, Y) Chart",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.scatter.scatter", label: "Scatter", ariaLabel: "Scatter", iconId: "chart" },
            { id: "insert.charts.scatter.smoothLines", label: "Scatter with Smooth Lines", ariaLabel: "Scatter with Smooth Lines", iconId: "chart" },
            { id: "insert.charts.scatter.more", label: "More Scatter Charts…", ariaLabel: "More Scatter Charts", iconId: "moreFormats" },
          ],
        },
        {
          id: "insert.charts.map",
          label: "Map",
          ariaLabel: "Insert Map Chart",
          iconId: "globe",
          kind: "dropdown",
          menuItems: [
            { id: "insert.charts.map.filledMap", label: "Filled Map", ariaLabel: "Filled Map", iconId: "globe" },
            { id: "insert.charts.map.more", label: "More Map Charts…", ariaLabel: "More Map Charts", iconId: "moreFormats" },
          ],
        },
        { id: "insert.charts.histogram", label: "Histogram", ariaLabel: "Insert Statistic Chart (Histogram, Pareto)", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.waterfall", label: "Waterfall", ariaLabel: "Insert Waterfall Chart", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.treemap", label: "Treemap", ariaLabel: "Insert Hierarchy Chart (Treemap)", iconId: "puzzle", kind: "dropdown" },
        { id: "insert.charts.sunburst", label: "Sunburst", ariaLabel: "Insert Hierarchy Chart (Sunburst)", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.funnel", label: "Funnel", ariaLabel: "Insert Funnel Chart", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.boxWhisker", label: "Box & Whisker", ariaLabel: "Insert Box and Whisker Chart", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.radar", label: "Radar", ariaLabel: "Insert Radar Chart", iconId: "globe", kind: "dropdown" },
        { id: "insert.charts.surface", label: "Surface", ariaLabel: "Insert Surface Chart", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.stock", label: "Stock", ariaLabel: "Insert Stock Chart", iconId: "chart", kind: "dropdown" },
        { id: "insert.charts.combo", label: "Combo", ariaLabel: "Insert Combo Chart", iconId: "shuffle", kind: "dropdown" },
        { id: "insert.charts.pivotChart", label: "PivotChart", ariaLabel: "PivotChart", iconId: "chart", kind: "dropdown" },
      ],
    },
    {
      id: "insert.tours",
      label: "Tours",
      buttons: [
        { id: "insert.tours.3dMap", label: "3D Map", ariaLabel: "3D Map", iconId: "globe", kind: "dropdown", size: "large" },
        { id: "insert.tours.launchTour", label: "Launch Tour", ariaLabel: "Launch Tour", iconId: "play", kind: "dropdown" },
      ],
    },
    {
      id: "insert.sparklines",
      label: "Sparklines",
      buttons: [
        {
          id: "insert.sparklines.line",
          label: "Line",
          ariaLabel: "Insert Line Sparkline",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [{ id: "insert.sparklines.line", label: "Line Sparkline…", ariaLabel: "Line Sparkline", iconId: "chart" }],
        },
        {
          id: "insert.sparklines.column",
          label: "Column",
          ariaLabel: "Insert Column Sparkline",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [{ id: "insert.sparklines.column", label: "Column Sparkline…", ariaLabel: "Column Sparkline", iconId: "chart" }],
        },
        {
          id: "insert.sparklines.winLoss",
          label: "Win/Loss",
          ariaLabel: "Insert Win/Loss Sparkline",
          iconId: "chart",
          kind: "dropdown",
          menuItems: [{ id: "insert.sparklines.winLoss", label: "Win/Loss Sparkline…", ariaLabel: "Win/Loss Sparkline", iconId: "chart" }],
        },
      ],
    },
    {
      id: "insert.filters",
      label: "Filters",
      buttons: [
        {
          id: "insert.filters.slicer",
          label: "Slicer",
          ariaLabel: "Insert Slicer",
          iconId: "cut",
          kind: "dropdown",
          menuItems: [
            { id: "insert.filters.slicer", label: "Slicer…", ariaLabel: "Insert Slicer", iconId: "cut" },
            { id: "insert.filters.slicer.reportConnections", label: "Report Connections…", ariaLabel: "Report Connections", iconId: "link" },
          ],
        },
        {
          id: "insert.filters.timeline",
          label: "Timeline",
          ariaLabel: "Insert Timeline",
          iconId: "clock",
          kind: "dropdown",
          menuItems: [{ id: "insert.filters.timeline", label: "Timeline…", ariaLabel: "Insert Timeline", iconId: "clock" }],
        },
      ],
    },
    {
      id: "insert.links",
      label: "Links",
      buttons: [{ id: "insert.links.link", label: "Link", ariaLabel: "Insert Link", iconId: "link", kind: "dropdown", size: "large" }],
    },
    {
      id: "insert.comments",
      label: "Comments",
      buttons: [
        { id: "insert.comments.comment", label: "Comment", ariaLabel: "Insert Comment", iconId: "comment", kind: "dropdown", size: "large" },
        { id: "insert.comments.note", label: "Note", ariaLabel: "Insert Note", iconId: "file", kind: "dropdown" },
      ],
    },
    {
      id: "insert.text",
      label: "Text",
      buttons: [
        { id: "insert.text.textBox", label: "Text Box", ariaLabel: "Insert Text Box", iconId: "edit", kind: "dropdown" },
        { id: "insert.text.headerFooter", label: "Header & Footer", ariaLabel: "Header and Footer", iconId: "file", kind: "dropdown" },
        { id: "insert.text.wordArt", label: "WordArt", ariaLabel: "WordArt", iconId: "fontColor", kind: "dropdown" },
        { id: "insert.text.signatureLine", label: "Signature Line", ariaLabel: "Signature Line", iconId: "edit", kind: "dropdown" },
        { id: "insert.text.object", label: "Object", ariaLabel: "Object", iconId: "file", kind: "dropdown" },
      ],
    },
    {
      id: "insert.equations",
      label: "Equations",
      buttons: [
        { id: "insert.equations.equation", label: "Equation", ariaLabel: "Insert Equation", iconId: "autoSum", kind: "dropdown", size: "large" },
        { id: "insert.equations.inkEquation", label: "Ink Equation", ariaLabel: "Ink Equation", iconId: "edit", kind: "dropdown" },
      ],
    },
    {
      id: "insert.symbols",
      label: "Symbols",
      buttons: [
        { id: "insert.symbols.equation", label: "Equation", ariaLabel: "Insert Equation", iconId: "autoSum", kind: "dropdown" },
        { id: "insert.symbols.symbol", label: "Symbol", ariaLabel: "Insert Symbol", iconId: "star", kind: "dropdown" },
      ],
    },
  ],
};
