import type { RibbonTabDefinition } from "../ribbonSchema.js";

export const viewTab: RibbonTabDefinition = {
  id: "view",
  label: "View",
  groups: [
    {
      id: "view.panels",
      label: "Panels",
      buttons: [
        {
          id: "view.togglePanel.marketplace",
          label: "Marketplace",
          ariaLabel: "Marketplace",
          iconId: "puzzle",
          testId: "open-marketplace-panel",
        },
        {
          id: "view.togglePanel.versionHistory",
          label: "Version History",
          ariaLabel: "Toggle Version History panel",
          iconId: "clock",
          testId: "open-version-history-panel",
        },
        {
          id: "view.togglePanel.branchManager",
          label: "Branches",
          ariaLabel: "Toggle Branch Manager panel",
          iconId: "shuffle",
          testId: "open-branch-manager-panel",
        },
      ],
    },
    {
      id: "view.appearance",
      label: "Appearance",
      buttons: [
        {
          id: "view.appearance.theme",
          label: "Theme",
          ariaLabel: "Theme",
          iconId: "palette",
          kind: "dropdown",
          testId: "theme-selector",
          menuItems: [
            {
              id: "view.appearance.theme.system",
              label: "System",
              ariaLabel: "Use system theme",
              iconId: "window",
              testId: "theme-option-system",
            },
            {
              id: "view.appearance.theme.light",
              label: "Light",
              ariaLabel: "Use light theme",
              iconId: "sun",
              testId: "theme-option-light",
            },
            {
              id: "view.appearance.theme.dark",
              label: "Dark",
              ariaLabel: "Use dark theme",
              iconId: "moon",
              testId: "theme-option-dark",
            },
            {
              id: "view.appearance.theme.highContrast",
              label: "High Contrast",
              ariaLabel: "Use high contrast theme",
              iconId: "shield",
              testId: "theme-option-high-contrast",
            },
          ],
        },
      ],
    },
    {
      id: "view.show",
      label: "Show",
      buttons: [
        { id: "view.show.ruler", label: "Ruler", ariaLabel: "Ruler", iconId: "ruler", kind: "toggle", defaultPressed: false },
        { id: "view.show.gridlines", label: "Gridlines", ariaLabel: "Gridlines", iconId: "gridlines", kind: "toggle", defaultPressed: true },
        { id: "view.show.formulaBar", label: "Formula Bar", ariaLabel: "Formula Bar", iconId: "function", kind: "toggle", defaultPressed: true },
        { id: "view.show.headings", label: "Headings", ariaLabel: "Headings", iconId: "headings", kind: "toggle", defaultPressed: true },
        {
          id: "view.toggleShowFormulas",
          label: "Show Formulas",
          ariaLabel: "Show formulas (Ctrl/Cmd+`)",
          iconId: "function",
          kind: "toggle",
          defaultPressed: false,
          testId: "ribbon-show-formulas",
        },
        {
          id: "view.togglePerformanceStats",
          label: "Performance Stats",
          ariaLabel: "Performance stats",
          iconId: "chart",
          kind: "toggle",
          defaultPressed: false,
          testId: "ribbon-perf-stats",
        },
      ],
    },
    {
      id: "view.zoom",
      label: "Zoom",
      buttons: [
        {
          id: "view.zoom.zoom",
          label: "Zoom",
          ariaLabel: "Zoom",
          iconId: "search",
          kind: "dropdown",
          size: "large",
          menuItems: [
            { id: "view.zoom.zoom400", label: "400%", ariaLabel: "Zoom 400%" },
            { id: "view.zoom.zoom200", label: "200%", ariaLabel: "Zoom 200%" },
            { id: "view.zoom.zoom150", label: "150%", ariaLabel: "Zoom 150%" },
            { id: "view.zoom.zoom100", label: "100%", ariaLabel: "Zoom 100%" },
            { id: "view.zoom.zoom75", label: "75%", ariaLabel: "Zoom 75%" },
            { id: "view.zoom.zoom50", label: "50%", ariaLabel: "Zoom 50%" },
            { id: "view.zoom.zoom25", label: "25%", ariaLabel: "Zoom 25%" },
            { id: "view.zoom.openPicker", label: "Custom…", ariaLabel: "Custom Zoom", iconId: "settings" },
          ],
        },
        { id: "view.zoom.zoom100", label: "100%", ariaLabel: "Zoom to 100%", iconId: "percent" },
        { id: "view.zoom.zoomToSelection", label: "Zoom to Selection", ariaLabel: "Zoom to Selection", iconId: "find" },
      ],
    },
    {
      id: "view.workbookViews",
      label: "Workbook Views",
      buttons: [
        { id: "view.workbookViews.normal", label: "Normal", ariaLabel: "Normal View", iconId: "gridlines", kind: "toggle", defaultPressed: true, size: "large" },
        { id: "view.workbookViews.pageBreakPreview", label: "Page Break Preview", ariaLabel: "Page Break Preview", iconId: "pageBreak", kind: "toggle", size: "large" },
        { id: "view.workbookViews.pageLayout", label: "Page Layout", ariaLabel: "Page Layout View", iconId: "pagePortrait", kind: "toggle", size: "large" },
        {
          id: "view.workbookViews.customViews",
          label: "Custom Views",
          ariaLabel: "Custom Views",
          iconId: "eye",
          kind: "dropdown",
          menuItems: [
            { id: "view.workbookViews.customViews", label: "Custom Views…", ariaLabel: "Custom Views", iconId: "eye" },
            { id: "view.workbookViews.customViews.manage", label: "Manage Views…", ariaLabel: "Manage Views", iconId: "settings" },
          ],
        },
      ],
    },
    {
      id: "view.window",
      label: "Window",
      buttons: [
        {
          id: "view.window.newWindow",
          label: "New Window",
          ariaLabel: "New Window",
          iconId: "window",
          kind: "dropdown",
          size: "large",
          menuItems: [
            { id: "view.window.newWindow", label: "New Window", ariaLabel: "New Window", iconId: "window" },
            { id: "view.window.newWindow.newWindowForActiveSheet", label: "New Window for Active Sheet", ariaLabel: "New Window for Active Sheet", iconId: "file" },
          ],
        },
        {
          id: "view.window.arrangeAll",
          label: "Arrange All",
          ariaLabel: "Arrange All",
          iconId: "window",
          kind: "dropdown",
          menuItems: [
            { id: "view.window.arrangeAll", label: "Arrange All…", ariaLabel: "Arrange All", iconId: "window" },
            { id: "view.window.arrangeAll.tiled", label: "Tiled", ariaLabel: "Tiled", iconId: "gridlines" },
            { id: "view.window.arrangeAll.horizontal", label: "Horizontal", ariaLabel: "Horizontal", iconId: "arrowLeftRight" },
            { id: "view.window.arrangeAll.vertical", label: "Vertical", ariaLabel: "Vertical", iconId: "arrowUpDown" },
            { id: "view.window.arrangeAll.cascade", label: "Cascade", ariaLabel: "Cascade", iconId: "window" },
          ],
        },
        {
          id: "view.window.freezePanes",
          label: "Freeze Panes",
          ariaLabel: "Freeze Panes",
          iconId: "lock",
          kind: "dropdown",
          menuItems: [
            { id: "view.freezePanes", label: "Freeze Panes", ariaLabel: "Freeze Panes", iconId: "lock" },
            { id: "view.freezeTopRow", label: "Freeze Top Row", ariaLabel: "Freeze Top Row", iconId: "arrowUp" },
            { id: "view.freezeFirstColumn", label: "Freeze First Column", ariaLabel: "Freeze First Column", iconId: "arrowLeft" },
            { id: "view.unfreezePanes", label: "Unfreeze Panes", ariaLabel: "Unfreeze Panes", iconId: "close" },
          ],
        },
        { id: "view.toggleSplitView", label: "Split", ariaLabel: "Split", iconId: "divide", kind: "toggle" },
        { id: "view.window.hide", label: "Hide", ariaLabel: "Hide", iconId: "eyeOff" },
        { id: "view.window.unhide", label: "Unhide", ariaLabel: "Unhide", iconId: "eye" },
        { id: "view.window.viewSideBySide", label: "View Side by Side", ariaLabel: "View Side by Side", iconId: "sideBySide", kind: "toggle" },
        { id: "view.window.synchronousScrolling", label: "Synchronous Scrolling", ariaLabel: "Synchronous Scrolling", iconId: "syncScroll", kind: "toggle" },
        { id: "view.window.resetWindowPosition", label: "Reset Window Position", ariaLabel: "Reset Window Position", iconId: "undo" },
        {
          id: "view.window.switchWindows",
          label: "Switch Windows",
          ariaLabel: "Switch Windows",
          iconId: "refresh",
          kind: "dropdown",
          menuItems: [
            { id: "view.window.switchWindows", label: "Switch Windows…", ariaLabel: "Switch Windows", iconId: "refresh" },
            { id: "view.window.switchWindows.window1", label: "Book1.xlsx", ariaLabel: "Switch to Book1", iconId: "file" },
            { id: "view.window.switchWindows.window2", label: "Forecast.xlsx", ariaLabel: "Switch to Forecast", iconId: "file" },
          ],
        },
      ],
    },
    {
      id: "view.macros",
      label: "Macros",
      buttons: [
        {
          id: "view.macros.viewMacros",
          label: "View Macros",
          ariaLabel: "View Macros",
          iconId: "file",
          kind: "dropdown",
          size: "large",
          testId: "ribbon-view-macros",
          menuItems: [
            { id: "view.macros.viewMacros", label: "View Macros…", ariaLabel: "View Macros", iconId: "file", testId: "ribbon-view-macros-open" },
            { id: "view.macros.viewMacros.run", label: "Run…", ariaLabel: "Run Macro", iconId: "play", testId: "ribbon-view-macros-run" },
            { id: "view.macros.viewMacros.edit", label: "Edit…", ariaLabel: "Edit Macro", iconId: "edit", testId: "ribbon-view-macros-edit" },
            { id: "view.macros.viewMacros.delete", label: "Delete…", ariaLabel: "Delete Macro", iconId: "trash", testId: "ribbon-view-macros-delete" },
          ],
        },
        {
          id: "view.macros.recordMacro",
          label: "Record Macro",
          ariaLabel: "Record Macro",
          iconId: "record",
          kind: "dropdown",
          testId: "ribbon-view-record-macro",
          menuItems: [
            { id: "view.macros.recordMacro", label: "Record Macro…", ariaLabel: "Record Macro", iconId: "record", testId: "ribbon-view-record-macro-start" },
            { id: "view.macros.recordMacro.stop", label: "Stop Recording", ariaLabel: "Stop Recording", iconId: "stop", testId: "ribbon-view-record-macro-stop" },
          ],
        },
        { id: "view.macros.useRelativeReferences", label: "Use Relative References", ariaLabel: "Use Relative References", iconId: "pin", kind: "toggle" },
      ],
    },
  ],
};
