import { describe, expect, it } from "vitest";

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import type { RibbonSchema } from "../ribbonSchema";
import { defaultRibbonSchema } from "../ribbonSchema";

function collectRibbonCommandIds(schema: RibbonSchema): string[] {
  const ids = new Set<string>();
  for (const tab of schema.tabs) {
    for (const group of tab.groups) {
      for (const button of group.buttons) {
        ids.add(button.id);
        for (const item of button.menuItems ?? []) {
          ids.add(item.id);
        }
      }
    }
  }
  return Array.from(ids).sort();
}

/**
 * All ribbon command ids that are expected to be explicitly handled by the
 * desktop app (currently in `apps/desktop/src/main.ts`).
 *
 * This list intentionally includes both:
 * - command ids that invoke real functionality, and
 * - command ids that are explicitly handled to avoid falling back to the default
 *   `showToast(\`Ribbon: ${commandId}\`)` implementation.
 *
 * If you add a new command id to `defaultRibbonSchema`, it must be added here
 * (when wired) or to `knownUnimplementedCommandIds` (when intentionally left
 * unwired).
 */
const implementedCommandIds: string[] = [
  "audit-dependents",
  "audit-precedents",
  "audit-transitive",
  "data.queriesConnections.queriesConnections",
  "data.queriesConnections.refreshAll",
  "data.queriesConnections.refreshAll.refresh",
  "data.queriesConnections.refreshAll.refreshAllConnections",
  "data.queriesConnections.refreshAll.refreshAllQueries",
  "developer.code.macroSecurity",
  "developer.code.macroSecurity.trustCenter",
  "developer.code.macros",
  "developer.code.macros.edit",
  "developer.code.macros.run",
  "developer.code.recordMacro",
  "developer.code.recordMacro.stop",
  "developer.code.useRelativeReferences",
  "developer.code.visualBasic",
  "file.export.changeFileType.csv",
  "file.export.changeFileType.pdf",
  "file.export.changeFileType.tsv",
  "file.export.changeFileType.xlsx",
  "file.export.createPdf",
  "file.export.export.csv",
  "file.export.export.pdf",
  "file.export.export.xlsx",
  "file.info.manageWorkbook.branches",
  "file.info.manageWorkbook.versions",
  "file.new.blankWorkbook",
  "file.new.new",
  "file.open.open",
  "file.options.close",
  "file.print.pageSetup",
  "file.print.pageSetup.margins",
  "file.print.pageSetup.printTitles",
  "file.print.print",
  "file.print.printPreview",
  "file.save.autoSave",
  "file.save.save",
  "file.save.saveAs",
  "file.save.saveAs.copy",
  "file.save.saveAs.download",
  "formulas.formulaAuditing.removeArrows",
  "formulas.formulaAuditing.showFormulas",
  "formulas.formulaAuditing.traceDependents",
  "formulas.formulaAuditing.tracePrecedents",
  "freeze-first-column",
  "freeze-panes",
  "freeze-top-row",
  "home.alignment.alignLeft",
  "home.alignment.alignRight",
  "home.alignment.bottomAlign",
  "home.alignment.center",
  "home.alignment.decreaseIndent",
  "home.alignment.increaseIndent",
  "home.alignment.middleAlign",
  "home.alignment.orientation.angleClockwise",
  "home.alignment.orientation.angleCounterclockwise",
  "home.alignment.orientation.formatCellAlignment",
  "home.alignment.orientation.rotateDown",
  "home.alignment.orientation.rotateUp",
  "home.alignment.orientation.verticalText",
  "home.alignment.topAlign",
  "home.alignment.wrapText",
  "home.cells.format.formatCells",
  "home.clipboard.copy",
  "home.clipboard.cut",
  "home.clipboard.formatPainter",
  "home.clipboard.paste",
  "home.clipboard.paste.default",
  "home.clipboard.paste.formats",
  "home.clipboard.paste.formulas",
  "home.clipboard.paste.transpose",
  "home.clipboard.paste.values",
  "home.clipboard.pasteSpecial",
  "home.clipboard.pasteSpecial.dialog",
  "home.clipboard.pasteSpecial.formats",
  "home.clipboard.pasteSpecial.formulas",
  "home.clipboard.pasteSpecial.transpose",
  "home.clipboard.pasteSpecial.values",
  "home.editing.autoSum",
  "home.editing.autoSum.sum",
  "home.editing.fill.down",
  "home.editing.fill.right",
  "home.editing.findSelect.find",
  "home.editing.findSelect.goTo",
  "home.editing.findSelect.replace",
  "home.font.bold",
  "home.font.borders",
  "home.font.borders.all",
  "home.font.borders.bottom",
  "home.font.borders.left",
  "home.font.borders.none",
  "home.font.borders.outside",
  "home.font.borders.right",
  "home.font.borders.thickBox",
  "home.font.borders.top",
  "home.font.clearFormatting.clearAll",
  "home.font.clearFormatting.clearContents",
  "home.font.clearFormatting.clearFormats",
  "home.font.decreaseFont",
  "home.font.fillColor",
  "home.font.fillColor.blue",
  "home.font.fillColor.green",
  "home.font.fillColor.lightGray",
  "home.font.fillColor.moreColors",
  "home.font.fillColor.none",
  "home.font.fillColor.red",
  "home.font.fillColor.yellow",
  "home.font.fontColor",
  "home.font.fontColor.automatic",
  "home.font.fontColor.black",
  "home.font.fontColor.blue",
  "home.font.fontColor.green",
  "home.font.fontColor.moreColors",
  "home.font.fontColor.red",
  "home.font.fontName.arial",
  "home.font.fontName.calibri",
  "home.font.fontName.courier",
  "home.font.fontName.times",
  "home.font.fontSize",
  "home.font.fontSize.10",
  "home.font.fontSize.11",
  "home.font.fontSize.12",
  "home.font.fontSize.14",
  "home.font.fontSize.16",
  "home.font.fontSize.18",
  "home.font.fontSize.20",
  "home.font.fontSize.24",
  "home.font.fontSize.28",
  "home.font.fontSize.36",
  "home.font.fontSize.48",
  "home.font.fontSize.8",
  "home.font.fontSize.9",
  "home.font.increaseFont",
  "home.font.italic",
  "home.font.strikethrough",
  "home.font.underline",
  "home.number.accounting",
  "home.number.accounting.eur",
  "home.number.accounting.gbp",
  "home.number.accounting.jpy",
  "home.number.accounting.usd",
  "home.number.comma",
  "home.number.date",
  "home.number.decreaseDecimal",
  "home.number.formatCells",
  "home.number.increaseDecimal",
  "home.number.moreFormats.custom",
  "home.number.moreFormats.formatCells",
  "home.number.numberFormat.accounting",
  "home.number.numberFormat.currency",
  "home.number.numberFormat.fraction",
  "home.number.numberFormat.general",
  "home.number.numberFormat.longDate",
  "home.number.numberFormat.number",
  "home.number.numberFormat.percentage",
  "home.number.numberFormat.scientific",
  "home.number.numberFormat.shortDate",
  "home.number.numberFormat.text",
  "home.number.numberFormat.time",
  "home.number.percent",
  "insert.tables.pivotTable",
  "open-ai-audit-panel",
  "open-ai-panel",
  "open-branch-manager-panel",
  "open-comments-panel",
  "open-data-queries-panel",
  "open-extensions-panel",
  "open-inline-ai-edit",
  "open-macros-panel",
  "open-marketplace-panel",
  "open-panel-ai-audit",
  "open-panel-ai-chat",
  "open-python-panel",
  "open-script-editor-panel",
  "open-vba-migrate-panel",
  "open-version-history-panel",
  "pageLayout.export.exportPdf",
  "pageLayout.pageSetup.margins.custom",
  "pageLayout.pageSetup.margins.narrow",
  "pageLayout.pageSetup.margins.normal",
  "pageLayout.pageSetup.margins.wide",
  "pageLayout.pageSetup.orientation.landscape",
  "pageLayout.pageSetup.orientation.portrait",
  "pageLayout.pageSetup.pageSetupDialog",
  "pageLayout.pageSetup.printArea.addTo",
  "pageLayout.pageSetup.printArea.clear",
  "pageLayout.pageSetup.printArea.set",
  "pageLayout.pageSetup.size.a4",
  "pageLayout.pageSetup.size.letter",
  "pageLayout.pageSetup.size.more",
  "pageLayout.printArea.clearPrintArea",
  "pageLayout.printArea.setPrintArea",
  "review.comments.newComment",
  "review.comments.showComments",
  "split-horizontal",
  "split-none",
  "split-vertical",
  "unfreeze-panes",
  "view.appearance.theme.dark",
  "view.appearance.theme.highContrast",
  "view.appearance.theme.light",
  "view.appearance.theme.system",
  "view.macros.recordMacro",
  "view.macros.recordMacro.stop",
  "view.macros.useRelativeReferences",
  "view.macros.viewMacros",
  "view.macros.viewMacros.delete",
  "view.macros.viewMacros.edit",
  "view.macros.viewMacros.run",
  "view.show.performanceStats",
  "view.show.showFormulas",
  "view.window.freezePanes.freezeFirstColumn",
  "view.window.freezePanes.freezePanes",
  "view.window.freezePanes.freezeTopRow",
  "view.window.freezePanes.unfreeze",
  "view.window.split",
  "view.zoom.zoom",
  "view.zoom.zoom.100",
  "view.zoom.zoom.150",
  "view.zoom.zoom.200",
  "view.zoom.zoom.25",
  "view.zoom.zoom.400",
  "view.zoom.zoom.50",
  "view.zoom.zoom.75",
  "view.zoom.zoom.custom",
  "view.zoom.zoom100",
  "view.zoom.zoomToSelection",
];

/**
 * All other ribbon command ids that exist in `defaultRibbonSchema` but are
 * intentionally not wired yet.
 */
const knownUnimplementedCommandIds: string[] = [
  "data.dataTools.consolidate",
  "data.dataTools.dataValidation",
  "data.dataTools.dataValidation.circleInvalid",
  "data.dataTools.dataValidation.clearCircles",
  "data.dataTools.flashFill",
  "data.dataTools.manageDataModel",
  "data.dataTools.manageDataModel.addToDataModel",
  "data.dataTools.relationships",
  "data.dataTools.relationships.manage",
  "data.dataTools.removeDuplicates",
  "data.dataTools.removeDuplicates.advanced",
  "data.dataTools.textToColumns",
  "data.dataTools.textToColumns.reapply",
  "data.dataTypes.geography",
  "data.dataTypes.stocks",
  "data.forecast.forecastSheet",
  "data.forecast.forecastSheet.options",
  "data.forecast.whatIfAnalysis",
  "data.forecast.whatIfAnalysis.dataTable",
  "data.forecast.whatIfAnalysis.goalSeek",
  "data.forecast.whatIfAnalysis.scenarioManager",
  "data.getTransform.existingConnections",
  "data.getTransform.getData",
  "data.getTransform.getData.fromAzure",
  "data.getTransform.getData.fromDatabase",
  "data.getTransform.getData.fromFile",
  "data.getTransform.getData.fromOnlineServices",
  "data.getTransform.getData.fromOtherSources",
  "data.getTransform.recentSources",
  "data.outline.group",
  "data.outline.group.group",
  "data.outline.group.groupSelection",
  "data.outline.hideDetail",
  "data.outline.showDetail",
  "data.outline.subtotal",
  "data.outline.ungroup",
  "data.outline.ungroup.clearOutline",
  "data.outline.ungroup.ungroup",
  "data.queriesConnections.properties",
  "data.sortFilter.advanced",
  "data.sortFilter.advanced.advancedFilter",
  "data.sortFilter.advanced.clearFilter",
  "data.sortFilter.clear",
  "data.sortFilter.filter",
  "data.sortFilter.reapply",
  "data.sortFilter.sort",
  "data.sortFilter.sort.customSort",
  "data.sortFilter.sort.sortAtoZ",
  "data.sortFilter.sort.sortZtoA",
  "data.sortFilter.sortAtoZ",
  "data.sortFilter.sortZtoA",
  "developer.addins.addins",
  "developer.addins.addins.browse",
  "developer.addins.addins.excelAddins",
  "developer.addins.addins.manage",
  "developer.addins.comAddins",
  "developer.controls.designMode",
  "developer.controls.insert",
  "developer.controls.insert.button",
  "developer.controls.insert.checkbox",
  "developer.controls.insert.combobox",
  "developer.controls.insert.listbox",
  "developer.controls.insert.scrollbar",
  "developer.controls.insert.spinButton",
  "developer.controls.properties",
  "developer.controls.properties.viewProperties",
  "developer.controls.runDialog",
  "developer.controls.viewCode",
  "developer.xml.export",
  "developer.xml.import",
  "developer.xml.mapProperties",
  "developer.xml.refreshData",
  "developer.xml.source",
  "developer.xml.source.refresh",
  "file.export.changeFileType",
  "file.export.export",
  "file.info.inspectWorkbook",
  "file.info.inspectWorkbook.checkAccessibility",
  "file.info.inspectWorkbook.checkCompatibility",
  "file.info.inspectWorkbook.documentInspector",
  "file.info.manageWorkbook",
  "file.info.manageWorkbook.properties",
  "file.info.manageWorkbook.recoverUnsaved",
  "file.info.protectWorkbook",
  "file.info.protectWorkbook.encryptWithPassword",
  "file.info.protectWorkbook.protectCurrentSheet",
  "file.info.protectWorkbook.protectWorkbookStructure",
  "file.new.fromExisting",
  "file.new.templates",
  "file.new.templates.budget",
  "file.new.templates.calendar",
  "file.new.templates.invoice",
  "file.new.templates.more",
  "file.open.pinned",
  "file.open.pinned.kpis",
  "file.open.pinned.q4",
  "file.open.recent",
  "file.open.recent.book1",
  "file.open.recent.budget",
  "file.open.recent.forecast",
  "file.open.recent.more",
  "file.options.account",
  "file.options.options",
  "file.share.email",
  "file.share.email.attachment",
  "file.share.email.link",
  "file.share.presentOnline",
  "file.share.share",
  "formulas.calculation.calculateNow",
  "formulas.calculation.calculateSheet",
  "formulas.calculation.calculationOptions",
  "formulas.definedNames.createFromSelection",
  "formulas.definedNames.defineName",
  "formulas.definedNames.nameManager",
  "formulas.definedNames.useInFormula",
  "formulas.formulaAuditing.errorChecking",
  "formulas.formulaAuditing.evaluateFormula",
  "formulas.formulaAuditing.watchWindow",
  "formulas.functionLibrary.autoSum",
  "formulas.functionLibrary.autoSum.average",
  "formulas.functionLibrary.autoSum.countNumbers",
  "formulas.functionLibrary.autoSum.max",
  "formulas.functionLibrary.autoSum.min",
  "formulas.functionLibrary.autoSum.moreFunctions",
  "formulas.functionLibrary.autoSum.sum",
  "formulas.functionLibrary.dateTime",
  "formulas.functionLibrary.financial",
  "formulas.functionLibrary.insertFunction",
  "formulas.functionLibrary.logical",
  "formulas.functionLibrary.lookupReference",
  "formulas.functionLibrary.mathTrig",
  "formulas.functionLibrary.moreFunctions",
  "formulas.functionLibrary.recentlyUsed",
  "formulas.functionLibrary.text",
  "formulas.solutions.analysisToolPak",
  "formulas.solutions.solver",
  "help.support.contactSupport",
  "help.support.feedback",
  "help.support.help",
  "help.support.training",
  "home.alignment.mergeCenter",
  "home.alignment.mergeCenter.mergeAcross",
  "home.alignment.mergeCenter.mergeCells",
  "home.alignment.mergeCenter.mergeCenter",
  "home.alignment.mergeCenter.unmergeCells",
  "home.alignment.orientation",
  "home.cells.delete",
  "home.cells.delete.deleteCells",
  "home.cells.delete.deleteSheet",
  "home.cells.delete.deleteSheetColumns",
  "home.cells.delete.deleteSheetRows",
  "home.cells.format",
  "home.cells.format.columnWidth",
  "home.cells.format.organizeSheets",
  "home.cells.format.rowHeight",
  "home.cells.insert",
  "home.cells.insert.insertCells",
  "home.cells.insert.insertSheet",
  "home.cells.insert.insertSheetColumns",
  "home.cells.insert.insertSheetRows",
  "home.clipboard.clipboardPane",
  "home.clipboard.clipboardPane.clearAll",
  "home.clipboard.clipboardPane.open",
  "home.clipboard.clipboardPane.options",
  "home.editing.autoSum.average",
  "home.editing.autoSum.countNumbers",
  "home.editing.autoSum.max",
  "home.editing.autoSum.min",
  "home.editing.autoSum.moreFunctions",
  "home.editing.clear",
  "home.editing.clear.clearAll",
  "home.editing.clear.clearComments",
  "home.editing.clear.clearContents",
  "home.editing.clear.clearFormats",
  "home.editing.clear.clearHyperlinks",
  "home.editing.fill",
  "home.editing.fill.left",
  "home.editing.fill.series",
  "home.editing.fill.up",
  "home.editing.findSelect",
  "home.editing.sortFilter",
  "home.editing.sortFilter.clear",
  "home.editing.sortFilter.customSort",
  "home.editing.sortFilter.filter",
  "home.editing.sortFilter.reapply",
  "home.editing.sortFilter.sortAtoZ",
  "home.editing.sortFilter.sortZtoA",
  "home.font.clearFormatting",
  "home.font.fontName",
  "home.font.subscript",
  "home.font.superscript",
  "home.number.moreFormats",
  "home.number.numberFormat",
  "home.styles.cellStyles",
  "home.styles.cellStyles.dataModel",
  "home.styles.cellStyles.goodBadNeutral",
  "home.styles.cellStyles.newStyle",
  "home.styles.cellStyles.numberFormat",
  "home.styles.cellStyles.titlesHeadings",
  "home.styles.conditionalFormatting",
  "home.styles.conditionalFormatting.clearRules",
  "home.styles.conditionalFormatting.colorScales",
  "home.styles.conditionalFormatting.dataBars",
  "home.styles.conditionalFormatting.highlightCellsRules",
  "home.styles.conditionalFormatting.iconSets",
  "home.styles.conditionalFormatting.manageRules",
  "home.styles.conditionalFormatting.topBottomRules",
  "home.styles.formatAsTable",
  "home.styles.formatAsTable.dark",
  "home.styles.formatAsTable.light",
  "home.styles.formatAsTable.medium",
  "home.styles.formatAsTable.newStyle",
  "insert.addins.getAddins",
  "insert.addins.myAddins",
  "insert.charts.area",
  "insert.charts.area.area",
  "insert.charts.area.more",
  "insert.charts.area.stackedArea",
  "insert.charts.bar",
  "insert.charts.bar.clusteredBar",
  "insert.charts.bar.more",
  "insert.charts.bar.stackedBar",
  "insert.charts.boxWhisker",
  "insert.charts.column",
  "insert.charts.column.clusteredColumn",
  "insert.charts.column.more",
  "insert.charts.column.stackedColumn",
  "insert.charts.column.stackedColumn100",
  "insert.charts.combo",
  "insert.charts.funnel",
  "insert.charts.histogram",
  "insert.charts.line",
  "insert.charts.line.line",
  "insert.charts.line.lineWithMarkers",
  "insert.charts.line.more",
  "insert.charts.line.stackedArea",
  "insert.charts.map",
  "insert.charts.map.filledMap",
  "insert.charts.map.more",
  "insert.charts.pie",
  "insert.charts.pie.doughnut",
  "insert.charts.pie.more",
  "insert.charts.pie.pie",
  "insert.charts.pivotChart",
  "insert.charts.radar",
  "insert.charts.recommendedCharts",
  "insert.charts.recommendedCharts.column",
  "insert.charts.recommendedCharts.line",
  "insert.charts.recommendedCharts.more",
  "insert.charts.recommendedCharts.pie",
  "insert.charts.scatter",
  "insert.charts.scatter.more",
  "insert.charts.scatter.scatter",
  "insert.charts.scatter.smoothLines",
  "insert.charts.stock",
  "insert.charts.sunburst",
  "insert.charts.surface",
  "insert.charts.treemap",
  "insert.charts.waterfall",
  "insert.comments.comment",
  "insert.comments.note",
  "insert.equations.equation",
  "insert.equations.inkEquation",
  "insert.filters.slicer",
  "insert.filters.slicer.reportConnections",
  "insert.filters.timeline",
  "insert.illustrations.icons",
  "insert.illustrations.onlinePictures",
  "insert.illustrations.pictures",
  "insert.illustrations.pictures.onlinePictures",
  "insert.illustrations.pictures.stockImages",
  "insert.illustrations.pictures.thisDevice",
  "insert.illustrations.screenshot",
  "insert.illustrations.shapes",
  "insert.illustrations.shapes.arrows",
  "insert.illustrations.shapes.basicShapes",
  "insert.illustrations.shapes.callouts",
  "insert.illustrations.shapes.flowchart",
  "insert.illustrations.shapes.lines",
  "insert.illustrations.shapes.rectangles",
  "insert.illustrations.smartArt",
  "insert.links.link",
  "insert.pivotcharts.pivotChart",
  "insert.pivotcharts.recommendedPivotCharts",
  "insert.sparklines.column",
  "insert.sparklines.line",
  "insert.sparklines.winLoss",
  "insert.symbols.equation",
  "insert.symbols.symbol",
  "insert.tables.pivotTable.fromDataModel",
  "insert.tables.pivotTable.fromExternal",
  "insert.tables.pivotTable.fromTableRange",
  "insert.tables.recommendedPivotTables",
  "insert.tables.table",
  "insert.text.headerFooter",
  "insert.text.object",
  "insert.text.signatureLine",
  "insert.text.textBox",
  "insert.text.wordArt",
  "insert.tours.3dMap",
  "insert.tours.launchTour",
  "pageLayout.arrange.align",
  "pageLayout.arrange.align.alignBottom",
  "pageLayout.arrange.align.alignCenter",
  "pageLayout.arrange.align.alignLeft",
  "pageLayout.arrange.align.alignMiddle",
  "pageLayout.arrange.align.alignRight",
  "pageLayout.arrange.align.alignTop",
  "pageLayout.arrange.bringForward",
  "pageLayout.arrange.group",
  "pageLayout.arrange.group.group",
  "pageLayout.arrange.group.regroup",
  "pageLayout.arrange.group.ungroup",
  "pageLayout.arrange.rotate",
  "pageLayout.arrange.rotate.flipHorizontal",
  "pageLayout.arrange.rotate.flipVertical",
  "pageLayout.arrange.rotate.rotateLeft90",
  "pageLayout.arrange.rotate.rotateRight90",
  "pageLayout.arrange.selectionPane",
  "pageLayout.arrange.sendBackward",
  "pageLayout.pageSetup.background",
  "pageLayout.pageSetup.background.background",
  "pageLayout.pageSetup.background.delete",
  "pageLayout.pageSetup.breaks",
  "pageLayout.pageSetup.breaks.insertPageBreak",
  "pageLayout.pageSetup.breaks.removePageBreak",
  "pageLayout.pageSetup.breaks.resetAll",
  "pageLayout.pageSetup.margins",
  "pageLayout.pageSetup.orientation",
  "pageLayout.pageSetup.printArea",
  "pageLayout.pageSetup.printTitles",
  "pageLayout.pageSetup.printTitles.printTitles",
  "pageLayout.pageSetup.size",
  "pageLayout.scaleToFit.height",
  "pageLayout.scaleToFit.height.1page",
  "pageLayout.scaleToFit.height.2pages",
  "pageLayout.scaleToFit.height.automatic",
  "pageLayout.scaleToFit.scale",
  "pageLayout.scaleToFit.scale.100",
  "pageLayout.scaleToFit.scale.70",
  "pageLayout.scaleToFit.scale.80",
  "pageLayout.scaleToFit.scale.90",
  "pageLayout.scaleToFit.scale.more",
  "pageLayout.scaleToFit.width",
  "pageLayout.scaleToFit.width.1page",
  "pageLayout.scaleToFit.width.2pages",
  "pageLayout.scaleToFit.width.automatic",
  "pageLayout.sheetOptions.gridlinesPrint",
  "pageLayout.sheetOptions.gridlinesView",
  "pageLayout.sheetOptions.headingsPrint",
  "pageLayout.sheetOptions.headingsView",
  "pageLayout.themes.colors",
  "pageLayout.themes.colors.colorful",
  "pageLayout.themes.colors.customize",
  "pageLayout.themes.colors.office",
  "pageLayout.themes.effects",
  "pageLayout.themes.effects.intense",
  "pageLayout.themes.effects.moderate",
  "pageLayout.themes.effects.subtle",
  "pageLayout.themes.fonts",
  "pageLayout.themes.fonts.aptos",
  "pageLayout.themes.fonts.customize",
  "pageLayout.themes.fonts.office",
  "pageLayout.themes.themes",
  "pageLayout.themes.themes.customize",
  "pageLayout.themes.themes.facet",
  "pageLayout.themes.themes.integral",
  "pageLayout.themes.themes.office",
  "review.changes.protectShareWorkbook",
  "review.changes.protectShareWorkbook.protectWorkbook",
  "review.changes.shareWorkbook",
  "review.changes.shareWorkbook.shareNow",
  "review.changes.trackChanges",
  "review.changes.trackChanges.highlight",
  "review.comments.deleteComment",
  "review.comments.deleteComment.deleteAll",
  "review.comments.deleteComment.deleteThread",
  "review.comments.next",
  "review.comments.previous",
  "review.ink.startInking",
  "review.language.language",
  "review.language.language.setProofing",
  "review.language.language.translate",
  "review.language.translate",
  "review.language.translate.translateSelection",
  "review.language.translate.translateSheet",
  "review.notes.editNote",
  "review.notes.newNote",
  "review.notes.showAllNotes",
  "review.notes.showHideNote",
  "review.proofing.accessibility",
  "review.proofing.smartLookup",
  "review.proofing.spelling",
  "review.proofing.spelling.thesaurus",
  "review.proofing.spelling.wordCount",
  "review.protect.allowEditRanges",
  "review.protect.allowEditRanges.new",
  "review.protect.protectSheet",
  "review.protect.protectWorkbook",
  "review.protect.unprotectSheet",
  "review.protect.unprotectWorkbook",
  "view.appearance.theme",
  "view.show.formulaBar",
  "view.show.gridlines",
  "view.show.headings",
  "view.show.ruler",
  "view.window.arrangeAll",
  "view.window.arrangeAll.cascade",
  "view.window.arrangeAll.horizontal",
  "view.window.arrangeAll.tiled",
  "view.window.arrangeAll.vertical",
  "view.window.freezePanes",
  "view.window.hide",
  "view.window.newWindow",
  "view.window.newWindow.newWindowForActiveSheet",
  "view.window.resetWindowPosition",
  "view.window.switchWindows",
  "view.window.switchWindows.window1",
  "view.window.switchWindows.window2",
  "view.window.synchronousScrolling",
  "view.window.unhide",
  "view.window.viewSideBySide",
  "view.workbookViews.customViews",
  "view.workbookViews.customViews.manage",
  "view.workbookViews.normal",
  "view.workbookViews.pageBreakPreview",
  "view.workbookViews.pageLayout",
];

const IMPLEMENTED_COMMAND_PREFIXES = [
  "home.font.fontName.",
  "home.font.fontSize.",
  "home.font.fillColor.",
  "home.font.fontColor.",
  "home.font.clearFormatting.",
  "home.font.borders.",
  "home.number.numberFormat.",
  "home.number.accounting.",
  "view.zoom.zoom.",
];

function extractImplementedCommandIdsFromMainTs(schemaCommandIds: Set<string>): string[] {
  const mainTsPath = fileURLToPath(new URL("../../main.ts", import.meta.url));
  const source = readFileSync(mainTsPath, "utf8");
  const ids = new Set<string>();

  const addIfSchema = (id: string) => {
    if (schemaCommandIds.has(id)) ids.add(id);
  };

  for (const match of source.matchAll(/case\\s+\"([^\"]+)\"/g)) {
    addIfSchema(match[1]!);
  }

  for (const match of source.matchAll(/commandId\\s*===\\s*\"([^\"]+)\"/g)) {
    addIfSchema(match[1]!);
  }

  const presentPrefixes = IMPLEMENTED_COMMAND_PREFIXES.filter((prefix) => source.includes(prefix));
  for (const id of schemaCommandIds) {
    if (presentPrefixes.some((prefix) => id.startsWith(prefix))) {
      ids.add(id);
    }
  }

  return Array.from(ids).sort();
}

describe("Ribbon command wiring coverage", () => {
  it("classifies every command id in defaultRibbonSchema as implemented vs intentionally unimplemented", () => {
    const schemaCommandIds = collectRibbonCommandIds(defaultRibbonSchema);

    // Guard against a broken traversal so the test can't pass vacuously.
    expect(schemaCommandIds).toContain("home.font.bold");
    expect(schemaCommandIds).toContain("home.number.numberFormat.currency");
    expect(schemaCommandIds).toContain("view.zoom.zoom.100");

    const implemented = new Set(implementedCommandIds);
    const knownUnimplemented = new Set(knownUnimplementedCommandIds);

    // Sanity checks on the lists themselves.
    const overlap = implementedCommandIds.filter((id) => knownUnimplemented.has(id));
    expect(overlap, `Command ids cannot be both implemented and known-unimplemented: ${overlap.join(", ")}`).toEqual([]);

    const unknown = schemaCommandIds.filter((id) => !implemented.has(id) && !knownUnimplemented.has(id));
    expect(
      unknown,
      `Found schema command ids with no wiring classification (add to implementedCommandIds or knownUnimplementedCommandIds):\n${unknown
        .map((id) => `- ${id}`)
        .join("\n")}`,
    ).toEqual([]);

    const extraImplemented = implementedCommandIds.filter((id) => !schemaCommandIds.includes(id));
    expect(
      extraImplemented,
      `implementedCommandIds contains ids that are not in defaultRibbonSchema:\n${extraImplemented.map((id) => `- ${id}`).join("\n")}`,
    ).toEqual([]);

    const extraKnownUnimplemented = knownUnimplementedCommandIds.filter((id) => !schemaCommandIds.includes(id));
    expect(
      extraKnownUnimplemented,
      `knownUnimplementedCommandIds contains ids that are not in defaultRibbonSchema:\n${extraKnownUnimplemented
        .map((id) => `- ${id}`)
        .join("\n")}`,
    ).toEqual([]);
  });

  it("keeps implementedCommandIds in sync with `apps/desktop/src/main.ts` ribbon wiring", () => {
    const schemaCommandIds = new Set(collectRibbonCommandIds(defaultRibbonSchema));
    const expected = extractImplementedCommandIdsFromMainTs(schemaCommandIds);
    expect(implementedCommandIds.slice().sort()).toEqual(expected);

    // Keep the denylist honest: it should always represent the remainder of schema ids.
    const expectedSet = new Set(expected);
    const remainder = Array.from(schemaCommandIds).filter((id) => !expectedSet.has(id)).sort();
    expect(knownUnimplementedCommandIds.slice().sort()).toEqual(remainder);
  });
});
