name: Bug report
description: Report a problem or regression
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser/app version, etc.
    validations:
      required: false

