import React from "react";

import type { IconProps } from "../../ui/icons/Icon";
import {
  AlignBottomIcon,
  AlignCenterIcon,
  AlignLeftIcon,
  AlignMiddleIcon,
  AlignRightIcon,
  AlignTopIcon,
  AutoSumIcon,
  BoldIcon,
  BordersIcon,
  CellStylesIcon,
  CloudIcon,
  CodeIcon,
  ClearFormattingIcon,
  ClearIcon,
  ClipboardPaneIcon,
  CommaIcon,
  ConditionalFormattingIcon,
  CopyIcon,
  CurrencyIcon,
  CutIcon,
  DeleteCellsIcon,
  DeleteSheetIcon,
  DecreaseDecimalIcon,
  DecreaseFontIcon,
  DecreaseIndentIcon,
  FillColorIcon,
  FillDownIcon,
  FilterIcon,
  FindIcon,
  FontColorIcon,
  FontSizeIcon,
  FormatAsTableIcon,
  FormatPainterIcon,
  FunctionIcon,
  GoToIcon,
  GridlinesIcon,
  HashIcon,
  HeadingsIcon,
  IncreaseDecimalIcon,
  IncreaseFontIcon,
  IncreaseIndentIcon,
  InsertCellsIcon,
  InsertColumnsIcon,
  InsertRowsIcon,
  InsertSheetIcon,
  ItalicIcon,
  MergeCenterIcon,
  MoreFormatsIcon,
  NumberFormatIcon,
  OrientationIcon,
  PageBreakIcon,
  PaletteIcon,
  PasteIcon,
  PasteSpecialIcon,
  PercentIcon,
  ReplaceIcon,
  RulerIcon,
  SideBySideIcon,
  SortFilterIcon,
  SortIcon,
  SparklesIcon,
  StrikethroughIcon,
  SubscriptIcon,
  SuperscriptIcon,
  SyncScrollIcon,
  UnderlineIcon,
  UndoIcon,
  RedoIcon,
  UnlockIcon,
  WrapTextIcon,
  LightningIcon,
} from "../../ui/icons";

import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowLeftRightIcon,
  ArrowRightIcon,
  ArrowUpDownIcon,
  ArrowUpIcon,
  CalendarIcon,
  ChartIcon,
  CheckIcon,
  ClockIcon,
  CommentIcon,
  DivideIcon,
  DownloadIcon,
  EditIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FilePlusIcon,
  FolderOpenIcon,
  GlobeIcon,
  HelpIcon,
  LinkIcon,
  LockIcon,
  MailIcon,
  MenuIcon,
  MinusIcon,
  PinIcon,
  TagIcon,
  PlayIcon,
  PlusIcon,
  PrintIcon,
  PuzzleIcon,
  RecordIcon,
  RefreshIcon,
  ReturnIcon,
  SaveIcon,
  SearchIcon,
  SettingsIcon,
  ShuffleIcon,
  StopIcon,
  TrashIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  WarningIcon,
  WindowIcon,
  XIcon,
  ImageIcon,
} from "./commonIcons.js";

type RibbonSvgIconProps = Omit<IconProps, "children">;

const ribbonIcons = {
  // File
  file: FileIcon,
  filePlus: FilePlusIcon,
  folderOpen: FolderOpenIcon,
  save: SaveIcon,
  print: PrintIcon,
  calendar: CalendarIcon,
  edit: EditIcon,

  // Common
  settings: SettingsIcon,
  ruler: RulerIcon,
  lock: LockIcon,
  unlock: UnlockIcon,
  search: SearchIcon,
  function: FunctionIcon,
  hash: HashIcon,
  clock: ClockIcon,
  pin: PinIcon,
  upload: UploadIcon,
  download: DownloadIcon,
  refresh: RefreshIcon,
  undo: UndoIcon,
  redo: RedoIcon,
  pageBreak: PageBreakIcon,
  tag: TagIcon,
  link: LinkIcon,
  mail: MailIcon,
  globe: GlobeIcon,
  user: UserIcon,
  users: UsersIcon,
  close: XIcon,
  check: CheckIcon,
  warning: WarningIcon,
  help: HelpIcon,
  trash: TrashIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  comment: CommentIcon,
  chart: ChartIcon,
  image: ImageIcon,
  puzzle: PuzzleIcon,
  window: WindowIcon,
  gridlines: GridlinesIcon,
  headings: HeadingsIcon,
  sideBySide: SideBySideIcon,
  syncScroll: SyncScrollIcon,
  shuffle: ShuffleIcon,
  cloud: CloudIcon,
  lightning: LightningIcon,
  code: CodeIcon,
  palette: PaletteIcon,
  sparkles: SparklesIcon,

  // Controls
  menu: MenuIcon,
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowLeftRight: ArrowLeftRightIcon,
  arrowUpDown: ArrowUpDownIcon,
  return: ReturnIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  divide: DivideIcon,
  play: PlayIcon,
  stop: StopIcon,
  record: RecordIcon,

  // Home (existing Cursor-style icons)
  paste: PasteIcon,
  pasteSpecial: PasteSpecialIcon,
  cut: CutIcon,
  copy: CopyIcon,
  formatPainter: FormatPainterIcon,
  clipboardPane: ClipboardPaneIcon,
  insertCells: InsertCellsIcon,
  insertRows: InsertRowsIcon,
  insertColumns: InsertColumnsIcon,
  insertSheet: InsertSheetIcon,
  deleteCells: DeleteCellsIcon,
  deleteSheet: DeleteSheetIcon,
  bold: BoldIcon,
  italic: ItalicIcon,
  underline: UnderlineIcon,
  strikethrough: StrikethroughIcon,
  subscript: SubscriptIcon,
  superscript: SuperscriptIcon,
  borders: BordersIcon,
  fillColor: FillColorIcon,
  fontColor: FontColorIcon,
  clearFormatting: ClearFormattingIcon,
  alignTop: AlignTopIcon,
  alignMiddle: AlignMiddleIcon,
  alignBottom: AlignBottomIcon,
  alignLeft: AlignLeftIcon,
  alignCenter: AlignCenterIcon,
  alignRight: AlignRightIcon,
  orientation: OrientationIcon,
  wrapText: WrapTextIcon,
  mergeCenter: MergeCenterIcon,
  increaseIndent: IncreaseIndentIcon,
  decreaseIndent: DecreaseIndentIcon,
  numberFormat: NumberFormatIcon,
  currency: CurrencyIcon,
  percent: PercentIcon,
  comma: CommaIcon,
  increaseDecimal: IncreaseDecimalIcon,
  decreaseDecimal: DecreaseDecimalIcon,
  moreFormats: MoreFormatsIcon,
  conditionalFormatting: ConditionalFormattingIcon,
  formatAsTable: FormatAsTableIcon,
  cellStyles: CellStylesIcon,
  increaseFont: IncreaseFontIcon,
  decreaseFont: DecreaseFontIcon,
  fontSize: FontSizeIcon,
  fillDown: FillDownIcon,
  clear: ClearIcon,
  find: FindIcon,
  replace: ReplaceIcon,
  sort: SortIcon,
  sortFilter: SortFilterIcon,
  filter: FilterIcon,
  goTo: GoToIcon,
  autoSum: AutoSumIcon,
} as const;

export type RibbonIconId = keyof typeof ribbonIcons;

export interface RibbonIconProps extends RibbonSvgIconProps {
  id: RibbonIconId;
}

export function RibbonIcon({ id, width, height, ...props }: RibbonIconProps) {
  const Component = ribbonIcons[id];
  return <Component width={width ?? "100%"} height={height ?? "100%"} {...props} />;
}
