// This file is generated by scripts/generate-function-catalog.js. Do not edit.
export default {
  "functions": [
    {
      "name": "ABS",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "AND",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "AVERAGE",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "CLEAN",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "CONCAT",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "CONCATENATE",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "COUNT",
      "min_args": 0,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "COUNTA",
      "min_args": 0,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "COUNTBLANK",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "COUNTIF",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "any"
      ]
    },
    {
      "name": "DATE",
      "min_args": 3,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number",
        "number"
      ]
    },
    {
      "name": "DATEVALUE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "DAY",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "DDB",
      "min_args": 4,
      "max_args": 5,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "DOLLAR",
      "min_args": 1,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "EDATE",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "EOMONTH",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "ERROR.TYPE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "EXACT",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "text",
        "text"
      ]
    },
    {
      "name": "FILTER",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any",
        "any"
      ]
    },
    {
      "name": "FIND",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "text",
        "text",
        "number"
      ]
    },
    {
      "name": "FV",
      "min_args": 3,
      "max_args": 5,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "GETPIVOTDATA",
      "min_args": 2,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "HLOOKUP",
      "min_args": 3,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any",
        "number",
        "any"
      ]
    },
    {
      "name": "HOUR",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "IF",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any",
        "any"
      ]
    },
    {
      "name": "IFERROR",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any"
      ]
    },
    {
      "name": "IFNA",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any"
      ]
    },
    {
      "name": "INDEX",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "number",
        "number"
      ]
    },
    {
      "name": "INT",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "IPMT",
      "min_args": 4,
      "max_args": 6,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "IRR",
      "min_args": 1,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "number"
      ]
    },
    {
      "name": "ISBLANK",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "ISERR",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "ISERROR",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "ISLOGICAL",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "ISNA",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "ISNUMBER",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "ISTEXT",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "LEFT",
      "min_args": 1,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text",
        "number"
      ]
    },
    {
      "name": "LEN",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "LOWER",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "MATCH",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "any",
        "number"
      ]
    },
    {
      "name": "MAX",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "MID",
      "min_args": 3,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text",
        "number",
        "number"
      ]
    },
    {
      "name": "MIN",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "MINUTE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "MIRR",
      "min_args": 3,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "number",
        "number"
      ]
    },
    {
      "name": "MOD",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "MONTH",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "N",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "NA",
      "min_args": 0,
      "max_args": 0,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": []
    },
    {
      "name": "NETWORKDAYS",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number",
        "any"
      ]
    },
    {
      "name": "NETWORKDAYS.INTL",
      "min_args": 2,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number",
        "any",
        "any"
      ]
    },
    {
      "name": "NOT",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "NOW",
      "min_args": 0,
      "max_args": 0,
      "volatility": "volatile",
      "return_type": "number",
      "arg_types": []
    },
    {
      "name": "NPER",
      "min_args": 3,
      "max_args": 5,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "NPV",
      "min_args": 2,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "any"
      ]
    },
    {
      "name": "NUMBERVALUE",
      "min_args": 1,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "text",
        "text",
        "text"
      ]
    },
    {
      "name": "OR",
      "min_args": 1,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "bool",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "PMT",
      "min_args": 3,
      "max_args": 5,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "PPMT",
      "min_args": 4,
      "max_args": 6,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "PROPER",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "PV",
      "min_args": 3,
      "max_args": 5,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "RAND",
      "min_args": 0,
      "max_args": 0,
      "volatility": "volatile",
      "return_type": "number",
      "arg_types": []
    },
    {
      "name": "RANDBETWEEN",
      "min_args": 2,
      "max_args": 2,
      "volatility": "volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "RATE",
      "min_args": 3,
      "max_args": 6,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "REPLACE",
      "min_args": 4,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text",
        "number",
        "number",
        "text"
      ]
    },
    {
      "name": "RIGHT",
      "min_args": 1,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text",
        "number"
      ]
    },
    {
      "name": "ROUND",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "ROUNDDOWN",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "ROUNDUP",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "SEARCH",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "text",
        "text",
        "number"
      ]
    },
    {
      "name": "SECOND",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "SEQUENCE",
      "min_args": 1,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "number",
        "number",
        "number",
        "number"
      ]
    },
    {
      "name": "SIGN",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "SLN",
      "min_args": 3,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "SORT",
      "min_args": 1,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "number",
        "number",
        "bool"
      ]
    },
    {
      "name": "SUBSTITUTE",
      "min_args": 3,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text",
        "text",
        "text",
        "number"
      ]
    },
    {
      "name": "SUM",
      "min_args": 0,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "SUMPRODUCT",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "any"
      ]
    },
    {
      "name": "SYD",
      "min_args": 4,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    },
    {
      "name": "T",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "TEXT",
      "min_args": 2,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "any",
        "text"
      ]
    },
    {
      "name": "TEXTJOIN",
      "min_args": 3,
      "max_args": 255,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text",
        "bool",
        "any"
      ]
    },
    {
      "name": "TIME",
      "min_args": 3,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number",
        "number"
      ]
    },
    {
      "name": "TIMEVALUE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "TODAY",
      "min_args": 0,
      "max_args": 0,
      "volatility": "volatile",
      "return_type": "number",
      "arg_types": []
    },
    {
      "name": "TRANSPOSE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "TRIM",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "TYPE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any"
      ]
    },
    {
      "name": "UNIQUE",
      "min_args": 1,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "bool",
        "bool"
      ]
    },
    {
      "name": "UPPER",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "text",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "VALUE",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "text"
      ]
    },
    {
      "name": "VLOOKUP",
      "min_args": 3,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any",
        "number",
        "any"
      ]
    },
    {
      "name": "WEEKDAY",
      "min_args": 1,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "WEEKNUM",
      "min_args": 1,
      "max_args": 2,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number"
      ]
    },
    {
      "name": "WORKDAY",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number",
        "any"
      ]
    },
    {
      "name": "WORKDAY.INTL",
      "min_args": 2,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "number",
        "any",
        "any"
      ]
    },
    {
      "name": "XIRR",
      "min_args": 2,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "any",
        "number"
      ]
    },
    {
      "name": "XLOOKUP",
      "min_args": 3,
      "max_args": 6,
      "volatility": "non_volatile",
      "return_type": "any",
      "arg_types": [
        "any",
        "any",
        "any",
        "any",
        "number",
        "number"
      ]
    },
    {
      "name": "XMATCH",
      "min_args": 2,
      "max_args": 4,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "any",
        "any",
        "number",
        "number"
      ]
    },
    {
      "name": "XNPV",
      "min_args": 3,
      "max_args": 3,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number",
        "any",
        "any"
      ]
    },
    {
      "name": "YEAR",
      "min_args": 1,
      "max_args": 1,
      "volatility": "non_volatile",
      "return_type": "number",
      "arg_types": [
        "number"
      ]
    }
  ]
};
