// This file is generated by scripts/generate-function-catalog.js. Do not edit.
declare const catalog: {
  functions: Array<{
    name: string;
    min_args: number;
    max_args: number;
    volatility: "non_volatile" | "volatile";
    return_type: "any" | "number" | "text" | "bool";
  }>;
};
export default catalog;
