export const RIBBON_DISABLED_BY_ID_WHILE_EDITING: Record<string, true> = {
  // --- Formatting ------------------------------------------------------------
  "home.font.subscript": true,
  "home.font.superscript": true,
  "home.alignment.mergeCenter": true,
  "home.alignment.mergeCenter.mergeCenter": true,
  "home.alignment.mergeCenter.mergeAcross": true,
  "home.alignment.mergeCenter.mergeCells": true,
  "home.alignment.mergeCenter.unmergeCells": true,
  // Custom number format prompt (disabled while editing; selection/format mutations are blocked).
  "home.number.moreFormats.custom": true,

  // --- Sheet structure -------------------------------------------------------
  "home.cells.format": true,
  "home.cells.format.rowHeight": true,
  "home.cells.format.columnWidth": true,
  "home.cells.format.organizeSheets": true,
  "home.cells.insert": true,
  "home.cells.insert.insertCells": true,
  "home.cells.insert.insertSheetRows": true,
  "home.cells.insert.insertSheetColumns": true,
  "home.cells.insert.insertSheet": true,
  "home.cells.delete": true,
  "home.cells.delete.deleteCells": true,
  "home.cells.delete.deleteSheetRows": true,
  "home.cells.delete.deleteSheetColumns": true,
  "home.cells.delete.deleteSheet": true,

  // --- Sort / Filter ---------------------------------------------------------
  "home.editing.sortFilter": true,
  "home.editing.sortFilter.sortAtoZ": true,
  "home.editing.sortFilter.sortZtoA": true,
  "home.editing.sortFilter.customSort": true,
  "home.editing.sortFilter.filter": true,
  "home.editing.sortFilter.clear": true,
  "home.editing.sortFilter.reapply": true,

  // --- Clear -----------------------------------------------------------------
  "home.editing.clear": true,
  "format.clearAll": true,
  "format.clearFormats": true,
  "edit.clearContents": true,
  "home.editing.clear.clearComments": true,
  "home.editing.clear.clearHyperlinks": true,

  // --- Home editing ----------------------------------------------------------
  "edit.autoSum": true,
  "home.editing.autoSum.average": true,
  "home.editing.autoSum.countNumbers": true,
  "home.editing.autoSum.max": true,
  "home.editing.autoSum.min": true,
  "home.editing.fill": true,
  "edit.fillDown": true,
  "edit.fillRight": true,
  "home.editing.fill.up": true,
  "home.editing.fill.left": true,
  "home.editing.fill.series": true,

  "data.sortFilter.sortAtoZ": true,
  "data.sortFilter.sortZtoA": true,
  "data.sortFilter.sort": true,
  "data.sortFilter.sort.customSort": true,
  "data.sortFilter.sort.sortAtoZ": true,
  "data.sortFilter.sort.sortZtoA": true,
  "data.sortFilter.filter": true,
  "data.sortFilter.clear": true,
  "data.sortFilter.reapply": true,
  "data.sortFilter.advanced": true,
  "data.sortFilter.advanced.advancedFilter": true,
  "data.sortFilter.advanced.clearFilter": true,
};
